### ISSUE TITLE
Toggle button not showing up

### ISSUE THREAD

**Issue by TysonRV** [farridav/django-jazzmin#10]
- Something is wrong with the toggle theme button, as it is just displaying a white square icon.

**Comment by TysonRV** [comment]
<img width="416" alt="Screenshot 2020-05-12 at 20 49 46" src="https://user-images.githubusercontent.com/22962693/81738821-398e8900-9492-11ea-9c5d-959e75604fc7.png">

**Comment by tnajun** [comment]
I have exactly the same problem. How do you fix it?
