### ISSUE TITLE
When login admin site as a staff doesn't show user menu

### ISSUE THREAD

**Issue by RetownPlato** [farridav/django-jazzmin#101]
When I  login  admin site as a staff, it doesn't show user menu.
![Screen Shot 2020-08-06 at 2.36.51 PM.png](https://i.loli.net/2020/08/06/t34xsmPdjFqkuCL.png)

**Comment by fengyouchao** [comment]
This bug has been fixed on the master branch.

**Comment by TysonRV** [comment]
Fixed on #98 

I just drafted a new release, it will be live soon. (2.2.6)

Thanks @fengyouchao for the fix!
