### ISSUE TITLE
Admin not show installed app

### ISSUE THREAD

**Issue by EhsanSafir** [farridav/django-jazzmin#104]
https://ibb.co/26yQP9M
![image](https://user-images.githubusercontent.com/58684770/89513202-83fd7880-d7e9-11ea-8d90-51f031b25b0d.png)
The installed app not loaded django 3.1

**Comment by TysonRV** [comment]
First Django 3.1 bug 😄 

We will review this, thanks for flagging @EhsanSafir !

**Comment by TysonRV** [comment]
This is not really happening to me... @EhsanSafir Could you share your `JAZZMIN_SETTINGS`?

**Comment by farridav** [comment]
Any app that comes through in plain old Django Admin *should* show up here, except under the following conditions:

- The model is disallowed using `'hide_models': [],` within your `JAZZMIN_SETTINGS` and it is the only model within that app
- The app is disallowed using `'hide_apps': [],` within your `JAZZMIN_SETTINGS`
- The app name uses capital letters (Bug fixed [here](https://github.com/farridav/django-jazzmin/pull/100) will be out in the next release V soon)

The first thing worth checking is does the app show up when you comment out "jazzmin" from `settings.INSTALLED_APPS`", if it does, and your not hiding it intentionally, then it might be something out side that we can look at ;)

**Comment by farridav** [comment]
Closing this, please reopen if the behaviour is unexpected, and reproducible given my previous comment
