### ISSUE TITLE
By Using AdminStackedInline this will divide into this to the new general tab

### ISSUE THREAD

**Issue by rjsh6697** [farridav/django-jazzmin#112]
How to stop this behaviour? please let me know. I am stuck in my Project

**Comment by farridav** [comment]
Have you tried using `"changeform_format": "single",` in your `JAZZMIN_SETTINGS` ?

.
This can be done for the whole site or a single model admin, see https://django-jazzmin.readthedocs.io/configuration/

Let me know if this fixes your issue.

**Comment by rjsh6697** [comment]
ok sir, let me try

**Comment by rjsh6697** [comment]
Yes sir its working as expected. Thanks
