### ISSUE TITLE
Enhancement: Template tag and base template to render custom forms in the admin

### ISSUE THREAD

**Issue by gkachru** [farridav/django-jazzmin#121]
While we can add links in the sidebar, top-menu to custom forms in the admin, a lot of work needs to be done to match the overall look of jazzmin.

A base template for custom forms to derive form and a template tag for render any form in jazzmin style would be great -- something like [django-bootstrap4](https://django-bootstrap4.readthedocs.io/en/latest/quickstart.html#example-template).

Using django-bootstrap4 directly causes some problems as bootstrap gets included twice (when we extend from jazzmin base.html) and it does not take on any of the jazzmin ui customizations.

**Comment by farridav** [comment]
Closing, feel free to provide more information and ill reopen it
