### ISSUE TITLE
Group selector height zero

### ISSUE THREAD

**Issue by txemavs** [farridav/django-jazzmin#140]
The selector-chosen height is set to 0px in auth/user permissions:
![jazz_group](https://user-images.githubusercontent.com/1844346/93207614-842f5300-f75b-11ea-84fc-a95c6e7cf412.png)

Disabling jazzmin:
![jazz_group_x](https://user-images.githubusercontent.com/1844346/93207809-ce183900-f75b-11ea-9801-bdd8bbe4cb14.png)

 May be JS fails to set selector-chosen height because the tab is not visible on load?

User permissions are ok:
![jazz_user](https://user-images.githubusercontent.com/1844346/93207713-a9bc5c80-f75b-11ea-854d-29f0937755b8.png)

**Comment by TysonRV** [comment]
@txemavs Hey mate! Thanks for reporting. That might be the issue, I'll take a look as soon as I can. 

If you want to try to fix it yourself, feel free to fork the repo and submit a PR!
