### ISSUE TITLE
Include custom CSS/JS in login template

### ISSUE THREAD

**Issue by chaduhduh** [farridav/django-jazzmin#145]
It would be neat to be able to inject custom CSS into login page similar to the functionality for admin templates.

I think a previous commit  which hasn't been released (7e892e2) resolves this issue but I just wanted to be able to track this.

**Comment by TysonRV** [comment]
@chaduhduh It is indeed a neat functionality and quite easy to implement. Thanks for the suggestion! We'll work on it shortly

**Comment by farridav** [comment]
Yeah we will put a release out today, and think about a way to show unreleased features.

Currently I do it with:

https://github.com/farridav/django-jazzmin/compare/v2.2.7...master

**Comment by TysonRV** [comment]
@chaduhduh Added to latest release https://github.com/farridav/django-jazzmin/releases/tag/v2.2.8
