### ISSUE TITLE
Field On Custom User Not Displayed If Fieldset Is None 

### ISSUE THREAD

**Issue by cglusky** [farridav/django-jazzmin#150]
I have a custom user that inherits from AbtractUser to add a phone number field.

UserAdmin is extended with 

```
...
fieldsets = BaseUserAdmin.fieldsets + ((None, {"fields": ("phone_number",)}),)
add_fieldsets = BaseUserAdmin.add_fieldsets + ((None, {"fields": ("phone_number",)}),)
...
```
The phone number field does not show in UI.  It appears to attempt to create another "General" tab but just populates it with username and password fields again.  

Adding the field to a fieldset works fine; this works as expected:

```
...
fieldsets = BaseUserAdmin.fieldsets + (("Phone", {"fields": ("phone_number",)}),)
add_fieldsets = BaseUserAdmin.add_fieldsets + (("Phone", {"fields": ("phone_number",)}),)
...
```

**Comment by farridav** [comment]
Ok, sink understand the problem properly, when adding multiple fieldsets with the same name (or no name), fields are not grouped or rendered e.g

```
fieldsets = (
    (None, ('field1', 'field2',)),
    (None, ('field3', 'field4')),
)
```

We are saying that in this instance, the second fieldset will not render, or will try to render out the first fieldset again.

I'd be keen to know how this works with jazzmin commented out of the installed apps, to see if it is our handling of the fieldsets.

Outcomes should be either:

- Django merges them together and renders them in the same fieldset
- Django renders them as separate fieldsets

**Comment by cglusky** [comment]
Thanks for having a look.  Add/change forms work just fine in Admin UI without jazzmin installed.  I started the project without and added later.

It's just one field and declaring "None" creates a field without a fieldset title in User admin forms.  If I name the fieldset something like "Phone" jazzmin works fine.  Here's the etire contents of admin.py for my core app that controls the custom User:

```
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import User


class UserAdmin(BaseUserAdmin):
    add_form = UserCreationForm
    form = UserChangeForm
    model = User
    list_display = (
        "pk",
        "last_name",
        "first_name",
        "username",
        "email",
        "phone_number",
    )

    fieldsets = BaseUserAdmin.fieldsets + (("Phone", {"fields": ("phone_number",)}),)
    add_fieldsets = BaseUserAdmin.add_fieldsets + (
        ("Phone", {"fields": ("phone_number",)}),
    )


admin.site.register(User, UserAdmin)
```

**Comment by farridav** [comment]
Ok, i have reproduced the problem here,

so when you do `BaseUserAdmin.fieldsets + (("Phone", {"fields": ("phone_number",)}),)` your not updating the data structure, your appending to it, giving you 2 fieldsets with the label `None`

```
((None, {'fields': ('username', 'password')}),
 ('Personal info', {'fields': ('first_name', 'last_name', 'email')}),
 ('Permissions',
  {'fields': ('is_active',
    'is_staff',
    'is_superuser',
    'groups',
    'user_permissions')}),
 ('Important dates', {'fields': ('last_login', 'date_joined')}),
 (None, {'fields': ('phone_number',)}))
```
When jazzmin renders this out, we make a tab for each fieldset, and we use the fieldset name as the unique identifier, in the case of no name, we use the name "General".

Because you have duplicate fieldset names, when you click on either of the duplicated tabs, its showing you the contents of the first one.

To fix this on your end i suggest something like:

```
    def get_fieldsets(self, request, obj=None):
        fieldsets = dict(super().get_fieldsets(request, obj=obj))
        fieldsets[None]["fields"] = fieldsets[None]["fields"] + ("phone",)
        return tuple((x, y) for x, y in fieldsets.items())
```
Which will add the `phone` field to the fieldset labeled `None` rather than duplicating the fieldset.

On a similar note, i might add a PR that forces tab ids to be unique, so the problem isnt masked, but i think it'd be a step too far to merge duplicate fieldsets together, as thats beyond jazzmins remit
 
I hope this all helps :) Ill reopen another issues to accurately reflect the problem

**Comment by cglusky** [comment]
Thanks very much for pointing me in a different direction.  Learn something new every day with Django.  In case someone ends up in here via google et al, I did have to add a conditional or the phone_number field gets added on every page refresh while in add/change forms.

```
def get_fieldsets(self, request, obj=None):
        fieldsets = dict(super().get_fieldsets(request, obj=obj))
        if "phone_number" not in fieldsets[None]["fields"]:
            fieldsets[None]["fields"] = fieldsets[None]["fields"] + ("phone_number",)
        return tuple((x, y) for x, y in fieldsets.items())
```

I did try directly declaring a new "None" fieldset with username, password, phone but it messes with the password confirmation, so just kept the concat with the conditional.

Thanks again!
