### ISSUE TITLE
Add option to customize model list order on the side menu

### ISSUE THREAD

**Issue by ClydeAmazing** [farridav/django-jazzmin#162]
Hello django-jazzmin team,

I love your work on django-jazzmin and I am currently using this in one of my projects.

Now, I would love to be able to sort model list on side menu much like the 'order_with_respect_to' option but for models. 
By default, django is sorting it alphabetically.

Maybe it can can be done like this:
'order_with_respect_to': ['accounts', 'accounts:orders', 'accounts:receivables', 'polls'],

or entirely different config option:
'order_models': ['accounts:orders', 'accounts:receivables'],

Or maybe this feature is already available and I totally miss this one out, please do let me know.

Thanks

**Comment by farridav** [comment]
This seems like a reasonable request, I'll see if I can have a crack at it tomorrow and get it into the next release.

Thanks for your interest in the project !

**Comment by ClydeAmazing** [comment]
Great! And thank you for creating this awesome project as well.

**Comment by ClydeAmazing** [comment]
The changes works wonderfully. Thanks!
