### ISSUE TITLE
Front end for add and edit broken

### ISSUE THREAD

**Issue by Labohkip81** [farridav/django-jazzmin#163]
```Request Method: | GET
-- | --
http://127.0.0.1:8000/admin/account/emailaddress/add/
3.0.10
TemplateDoesNotExist
django/forms/widgets/input.html
/home/gg/.local/share/virtualenvs/r-wlGvbENL/lib/python3.8/site-packages/django/template/backends/django.py in reraise, line 84
/home/gg/.local/share/virtualenvs/real-wlGvbENL/bin/python3
3.8.5
  '/home/gg/Dev/Current_projects/realsources_africa',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/home/gg/.local/share/virtualenvs/realsources_africa-wlGvbENL/lib/python3.8/site-packages',',
````

**Comment by farridav** [comment]
Interesting, though jazzmin does not render any templates (except for the select widgets), it only overrides them, and expects the template engine to grab our copy of the HTML file in place of djangos one.

1. If you comment out "jazzmin", from your INSTALLED_APPS, does the problem persist ?
2. What does your EmailAddressAdmin class look like ?

In the meantime, I will try to reproduce the problem using our embedded test app

**Comment by Labohkip81** [comment]
1. EmailAddressAdmin class is the default one that comes with django.

**Comment by Labohkip81** [comment]
Found the source of the error i didn't have django.forms included in the installed apps. Thanks.
