### ISSUE TITLE
models.DurationField and models.Charfield(choices=choices) not rendering properly

### ISSUE THREAD

**Issue by ClydeAmazing** [farridav/django-jazzmin#166]
Hello @farridav,

django-jazzmin renders forms very nicely, however, it doesn't properly render the following model fields in my case:
models.DurationField 
models.Charfield(choices=custom_choices)  --> (dropdown menu)

![image](https://user-images.githubusercontent.com/16679098/95204227-5e571480-0816-11eb-921a-a78c6d0d2140.png)

I can, however, get around this by adding ModelForm and defining custom widget or add class attributes (e.g. vTextField) to each problematic fields. 

It sounded to me like it is not a desired behavior that's why I am raising this issue.

Thank you.

**Comment by TysonRV** [comment]
Hi @ClydeAmazing , thanks for your comment. We are aware of those issues happening, but we are currently thinking on the best approach for it.

As you may know already, the way Django injects the fields of a model is not always that consistent and it gets therefore a bit tricky to jazz up all fields. 

We will keep you updated!
