### ISSUE TITLE
Compatibility with django-mptt

### ISSUE THREAD

**Issue by dimastbk** [farridav/django-jazzmin#169]
Hi!

Can you replace `<table class="table table-striped">` with `<table id="result_list" class="table table-striped">` in `change_list_results.html`? (This "id" is in the original django admin.) This want for compability with `DraggableMPTTAdmin` from [django-mptt](https://github.com/django-mptt/django-mptt).

Also, this style impove view DraggableMPTTAdmin in jazzmin
```
#result_list .field-tree_actions {
    width: calc(40px + 2.25rem);
}

#result_list .field-tree_actions > div {
    margin-top: 0;
}
```

Thanks.

**Comment by dimastbk** [comment]
Also, `TreeRelatedFieldListFilter` is broken in jazzmin. But i don't know, how well fixed it.

**Comment by farridav** [comment]
Sure this seems quite reasonable, ill take a look today

**Comment by farridav** [comment]
I've been looking through this, and its not as simple as i had hoped, django-mptt seem to be using their own templates (see https://github.com/django-mptt/django-mptt/tree/master/mptt/templates/admin)

and regardless of where in `INSTALLED_APPS` i put `mptt` I never get the right template, my WIP branch is here https://github.com/farridav/django-jazzmin/pull/170

Im trying to see if i can affect the template, but as a last resort, we can add necessary styling through CSS, or use JS

So far, the page doesnt look as expected, though i may not have MPTT configured properly, happy to receive guidance on this..

**Comment by farridav** [comment]
Ok, i have it all rendering out nicely now, thanks .. i just need to get the tests updated, and we will get it in ..
