### ISSUE TITLE
Broken tabular inline

### ISSUE THREAD

**Issue by dimastbk** [farridav/django-jazzmin#179]
2.2.11 release:
![изображение](https://user-images.githubusercontent.com/3132181/95823283-a58e5980-0d70-11eb-8ef9-0854b228c733.png)

master:
![изображение](https://user-images.githubusercontent.com/3132181/95823433-f605b700-0d70-11eb-9332-2f290a7b38fb.png)

**Comment by farridav** [comment]
Is this still an issue in master ? We cant seem to reproduce it ?

**Comment by farridav** [comment]
Closing as we cannot repro on master, feel free to reopen if we have missed something, and we will give it a proper run through
