### ISSUE TITLE
How do I hide the "View on site" link in TabularInline

### ISSUE THREAD

**Issue by valerytar** [farridav/django-jazzmin#186]
How is it possible not to display the first column (__str__ model method + 'View on site') of the inline form ?
I didn't find any option to set this.
Thanks

**Comment by farridav** [comment]
From what I can see, this is generated when you have a get_absolute_url method in your model.

You could hide it using custom CSS, does it come up when jazzmin is commented out of installed apps ?

**Comment by valerytar** [comment]
Yes if the get_absolute_url is not implemented, then the "View on site" is not shown.
But the first column is still always displayed (based on the __str__ method of the model object).
I've probably miswritten the issue. The question is "How can this column be displayed or not based on the AdminForm ?"
If I overwrite the CSS, it will be invisible for all the models...
Thanks!

**Comment by farridav** [comment]
I see what you mean now, let me take a look at this, perhaps theres a way we can disable it, or make it less space consuming, like in the original Django.. @TysonRV .. perhaps you can help on this one, since you recently did a lot of work on the inlines ;)

**Comment by farridav** [comment]
Im going to remove the __str__ repr on tabular, and move the View on site test into the a tags title, which will leave it looking like 
![image](https://user-images.githubusercontent.com/2966253/98444695-01979400-210b-11eb-93e2-3e1f75de6ff3.png)

I hope this solves your problem, I too agree that it doesnt fit within the tabular layout
