### ISSUE TITLE
Demo App seems broken

### ISSUE THREAD

**Issue by Varkal** [farridav/django-jazzmin#194]
Hi !

Can't connect to the demo app with test@test.com and test credentials

**Comment by farridav** [comment]
:( it seems some troll has changed the password again, and I've not invested the time to lock it down properly.

I'll force a dB reset shortly and update this ticket when done

**Comment by farridav** [comment]
The test user is back on and the data has been reset, im curious to know how it was changed, as i put in some very basic countermeasures

**Comment by Varkal** [comment]
Thanks you !
