### ISSUE TITLE
Max width in login form with error

### ISSUE THREAD

**Issue by marcorichetta** [farridav/django-jazzmin#198]
I would like to suggest to define a `max-width: ~700px` for the login form, or at least when there are errors. 

### Default form

<img src="https://user-images.githubusercontent.com/19599150/97881091-b6434700-1d00-11eb-8d69-5a22eec289d5.png" width="400">

### Default form with error
<img src="https://user-images.githubusercontent.com/19599150/97881325-03bfb400-1d01-11eb-81db-035bc3efbc96.png" width="800">

### Max width 700px
<img src="https://user-images.githubusercontent.com/19599150/97882006-de7f7580-1d01-11eb-8206-bbd71f970ca3.png" width="400">

**Comment by farridav** [comment]
That seems reasonable, perhaps you want to make a PR for this ?

**Comment by marcorichetta** [comment]
Sure! :+1:
