### ISSUE TITLE
utils.get_admin_url goes wrong for apps named with camel case

### ISSUE THREAD

**Issue by mpibpc-mroose** [farridav/django-jazzmin#203]
I think there may be a problem with [get_admin_url](https://github.com/farridav/django-jazzmin/blob/2b51e6ee1efeaea415376a4fe6b1175d2362e1ad/jazzmin/utils.py#L49) and apps named in CamelCase.

Given we have an app named `CamelStore` and inside a model named `CamelType` the admin change list name for that would be `admin:CamelStore_cameltype_changelist`. As `get_admin_url`  converts the whole string with `lower()` that would result in a non resolvable admin url.

Just removing the `lower()`call in  [line 50](https://github.com/farridav/django-jazzmin/blob/2b51e6ee1efeaea415376a4fe6b1175d2362e1ad/jazzmin/utils.py#L50) should solve that problem.

_Originally posted by @mpibpc-mroose in https://github.com/farridav/django-jazzmin/issues/99#issuecomment-721690070_

**Comment by farridav** [comment]
Sounds like a real easy fix with a real easy test, if you have the capacity, perhaps you could make a PR for it ? 

If not then somebody else will pick it up soon, I'm just stretched a little thin at the moment

**Comment by mpibpc-mroose** [comment]
No problem, I already "prototyped" something for the fix. 

The main problem is that we need to extend the sample Django project for that. We need a (camel cased) app and some model and admin inside becaus we need some admin url for testing. I don't want to "destroy" your great sample project. So maybe you want to suggest some app and project name and "user story" for that?

**Comment by farridav** [comment]
We should be able to test the function without adding a new model, I'll have a think about how ..

**Comment by mpibpc-mroose** [comment]
We always have two steps: 
1. extract appname and modelname
2. convert that to the actual admin url.

So a bit of refactoring and splitting that up might be a possible solution. Then we can test the "reversing" and the extraction of appname and modelname separatly which would not require the extension of the sample model. 

I have something in mind which I will try to implement tomorow.

**Comment by farridav** [comment]
The easiest way is probably to monkey patch model meta, then pass the model into the function..

If your able to do this, I'd gladly take a look, if not I can come up with an example of the patching

**Comment by mpibpc-mroose** [comment]
There seem to be more problems with camel cased projects. E.g. 

```
JAZZMIN_SETTINGS = {

    ...

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    'topmenu_links': [
        {'app': 'BookShelf'},
    ],
    
    ....
}
```
would not create a menu for the BookShelf app. I identified `utils.get_view_permissions` as root cause as it calls `lower()` on the model permission. Will try to append some fix for that in my PR, too.
