### ISSUE TITLE
Missing staticfiles manifest entry for '%s'" % clean_name)

### ISSUE THREAD

**Issue by jamesreinhold** [farridav/django-jazzmin#216]
After deploying application on heroku, it raized this error

```
raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
2020-11-16T15:50:12.844857+00:00 app[web.1]: ValueError: Missing staticfiles manifest entry for 'adminlte/plugins/jquery/jquery-3.5.1.slim.min.js'
```

this is referencing a static file that doesn't exist.  And if i am right, there is an already referenced file:

`<script src="{% static 'vendor/jquery/jquery-3.5.1.slim.min.js' %}"></script>`

Check the login.html

**Comment by farridav** [comment]
Oh noes ! I'll take a look at this tonight and try to get a hotfix out

**Comment by farridav** [comment]
Ok 2.4.1 should now be published .. now thats what i call a hotfix  :fire:
