### ISSUE TITLE
Some elements need additional styling when a selected theme is a dark one. 

### ISSUE THREAD

**Issue by hwalinga** [farridav/django-jazzmin#219]
A continuation of #192 

Some elements aren't proper bootstrap elements and need manual styling when the selected theme is a dark one. 

These elements are:

* The login page: 
  - .login-page, .register-page
  - .login-card-body, .register-card-body
* The "timeline":
  - .timeline > div > .timeline-item
  - .timeline > div > .timeline-item > .time

The last one requires a `color` to be set for the text color, the others just a `background`. 

The header: A simple and clean work-around for this is set `"navbar": "navbar-dark bg-primary"` in the `JAZZMIN_UI_TWEAKS`.

You probably can solve this with just loading like four lines of additional CSS when a dark theme is selected.

**Comment by farridav** [comment]
I was hoping there would be some follow up tweaks for dark mode, and it seems like you have a fairly clear idea of some things that need doing.

Perhaps you can make a PR  instead ?

**Comment by hwalinga** [comment]
I could, but my sense for colors is horrible and I am not a dark theme user. 

But I can make a draft and then you can change the colors to something more pleasing to the dark theme users.

**Comment by farridav** [comment]
Perhaps there are bootstrap classes or changes in the markup that we could make to these elements to help them fall in line with the theme ?

I'll take a look at this too when I can .

**Comment by hwalinga** [comment]
Hmmm... Well I am not very familiar with Bootstrap either...

But let's see what I make of it. I just thought of loading in some custom CSS when the theme is a dark one.

**Comment by farridav** [comment]
Probably no need for a new static file, as we can target themes using CSS selectors, I'll take a look too, I'm quite familiar with bootstrap and adminlte.

Anything that looks out of place, is usually something we can remedy by using the right markup or bootstrap classes .

I'll also take a look at this early next week
