### ISSUE TITLE
write custom views for admin

### ISSUE THREAD

**Issue by linhnvhicts** [farridav/django-jazzmin#222]
Hello i'm trying to write a custom views for the django admin, the problem i'm having is the sidebar app doesn't render. Here is my custom view:
```
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.admin import AdminSite
class MyAdminSite(AdminSite):
            pass
mysite = MyAdminSite()

# Create your views here.
@staff_member_required
def student_profile(request):
    if request.method == 'GET':
        return render(request, 
                    'student_profile.html', 
                    {
                        'site_header': mysite.site_header,
                        'has_permission': mysite.has_permission(request), 
                        'site_url': mysite.site_url                    }
                )
```
The custom view render perfectly but the sidebar don't have any apps list display

![Screen Shot 2020-12-01 at 2 03 11 PM](https://user-images.githubusercontent.com/46511495/100707897-fec45200-33dd-11eb-9bca-9ab1e7a2436b.png)

I tried to render those context with other django custom admin template(django-baton, django-suit) and the apps list show normally, it doesn't seem to work for only jazzmin. What else do i need to pass to the template for the sidebar app list to show?

in your jazzmin.py i see that you having custom template tags that accept `available_apps` 
https://github.com/farridav/django-jazzmin/blob/f908d92c0ce8aaad33653f80df4ec844bdbb83de/jazzmin/templatetags/jazzmin.py#L43

i tried to add 
```
'available_apps': mysite.get_app_list(request)
```
but it doesn't seem to work either

**Comment by farridav** [comment]
When you added available apps into the context, what did it have in it?  I fear it was an empty list, That's all that's required for the render...

I'll take a look at this today, I think I recall being able to grab available apps from somewhere else if it's not available in the context

**Comment by linhnvhicts** [comment]
@farridav you are right, i tried to check `mysite.get_app_list(request)` and indeed it was an empty list. I wonder why because i'm login as super user which should have all the permission

**Comment by farridav** [comment]
Im not entirely sure on the validity of this approach to adding custom views to the admin, the way ive seen it done before is something like this https://medium.com/@adriennedomingus/adding-custom-views-or-templates-to-django-admin-740640cc6d42

This way the template render will get all of the usual context, and you can add your own on top by overriding the methods in your admin class.

Im keen to know the right way forwards here, as id like to be able to add an example into the docs..

**Comment by linhnvhicts** [comment]
@farridav i tried your link method and it has no effect 
```
from django.contrib import admin
from .models import *
# Register your models here.
from django.conf.urls import url
from django.contrib import admin
from .views import student_profile
class CustomAdminSite(admin.AdminSite):
  
    def get_urls(self):
        urls = super(CustomAdminSite, self).get_urls()
        custom_urls = [
            url(r'student-profile$', student_profile, name="student_profile"),
        ]
        return urls + custom_urls

admin_site = CustomAdminSite()
admin_site.register(LearningPurpose)
admin_site.register(ClassProblem)
admin_site.register(DayInWeek)
admin_site.register(School)
admin_site.register(Language)
```
i also changed all admin.site to admin_site

![Screen Shot 2020-12-01 at 4 39 53 PM](https://user-images.githubusercontent.com/46511495/100723042-de06f700-33f3-11eb-9544-4fda295b4610.png)

i don't know why it not working
I think it's because i used render() in my view, most of the example only use httpResponse

**Comment by linhnvhicts** [comment]
i figured it out, i wasn't using the correct one as Django docs
```
class CustomAdminSite(admin.AdminSite):
  
    def get_urls(self):
        urls = super(CustomAdminSite, self).get_urls()
        custom_urls = [
            path('student-profile/', self.student_profile ,name="student_profile"),
        ]
        return urls + custom_urls
    
    def student_profile(self, request):
        if request.method == 'GET':
            context = dict(
            # Include common variables for rendering the admin template.
            self.each_context(request),
            # Anything else you want in the context...
            )
            return TemplateResponse(request, "student_profile.html", context)
```
now this is the correct 
https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_urls
![Screen Shot 2020-12-01 at 5 08 25 PM](https://user-images.githubusercontent.com/46511495/100726773-f6791080-33f7-11eb-888c-c447e409b24a.png)

Thank you for helping :D

**Comment by farridav** [comment]
Cool :) glad your enjoying jazzmin :)

**Comment by leagurru** [comment]
> admin_site = CustomAdminSite()

Could you post your views.py and admin.py, and urls.py please ? I'm trying your solution but doesn't works.
My intention is to add a custom view to an djando admin app
Thanks
