### ISSUE TITLE
re-"list" of the returned choices

### ISSUE THREAD

**Issue by h55nick** [farridav/django-jazzmin#223]
Think there is a bug here:
https://github.com/farridav/django-jazzmin/blob/f908d92c0ce8aaad33653f80df4ec844bdbb83de/jazzmin/templatetags/jazzmin.py#L213
where the returned choices should already be a list, and re-listing causes the following errors:

Code:
```/usr/local/lib/python3.8/site-packages/jazzmin/templatetags/jazzmin.py in jazzmin_list_filter
@register.simple_tag
def jazzmin_list_filter(cl: ChangeList, spec: BooleanFieldListFilter) -> SafeText:
    tpl = get_template(spec.template)
    choices = list(spec.choices(cl))
    field_key = get_filter_id(spec)
    matched_key = field_key
    for choice in choices:
        query_string = choice["query_string"][1:] …
        query_parts = urllib.parse.parse_qs(query_string)
```

Images:
![Screen Shot 2020-12-04 at 3 03 17 PM](https://user-images.githubusercontent.com/2540231/101209534-e2c0ea80-3641-11eb-9b1e-8e67e07b12fb.png)
![Screen Shot 2020-12-04 at 3 03 25 PM](https://user-images.githubusercontent.com/2540231/101209535-e3598100-3641-11eb-98fd-611ae453fbc2.png)

This is because the "choice" is not the entire list returned from choices.

This is happening for a modified:
admin.DateFieldListFilter

with the following custom template:
```
{% load i18n %}
<script type="text/javascript">var go_from_select = function(opt) { window.location = window.location.pathname + opt };</script>
<h3>{% blocktrans with title as filter_title %} By {{ filter_title }} {% endblocktrans %}</h3>
<ul class="admin-filter-{{ title|cut:' ' }}">
    <li>
        <div>
            <label style="width: 25%; display: inline-block;">Month</label>
            <select style="width: 70%;" class="form-control" onchange="go_from_select(this.options[this.selectedIndex].value)">
            {% with choices|first as month_choices %}
                {% for choice in month_choices %}
                    <option {% if choice.selected %} selected="selected"{% endif %} value="{{ choice.query_string|iriencode }}">{{ choice.display }}</option>
                {% endfor %}
            {% endwith %}
            </select>
        </div>
        <div>
            <label style="width: 25%; display: inline-block;">Year</label>
            <select style="width: 70%;" class="form-control" onchange="go_from_select(this.options[this.selectedIndex].value)">
        {% with choices|last as year_choices %}
                {% for choice in year_choices %}
                    <option {% if choice.selected %} selected="selected"{% endif %} value="{{ choice.query_string|iriencode }}">{{ choice.display }}</option>
                {% endfor %}
        {% endwith %}
            </select>
        </div>
    </li>
</ul>
```

Perhaps I'm missing something but would think choices would already be enumerated and not need "re-listing"?

**Comment by farridav** [comment]
This is the second issue we have seen with this template tag, It's something we inherited a long time ago, and I'm keen to get it sorted.

I'll try to take a look this weekend and reproduce the issue.

Thanks for reporting

**Comment by farridav** [comment]
Ive been struggling to reproduce this issue easily, our implementation of the list_filter template tag isnt too much different from djangos, we just reshape the choices a little bit to allow them to render out in a select.

id been keen to know the value of `choice` when you raise that exception, or better still, if your able to reproduce the problem by jacking on the code in our [demo app](https://github.com/farridav/django-jazzmin/tree/master/tests/test_app) then ill be able to try and resolve from there.

**Comment by farridav** [comment]
slightly unrelated, but perhaps `date_hierarchy = "published_on"`  would help with your use case? we render out year and month buttons for drilling down through date hierarchies .

If you can provide me with a way to repro in our demo app, ill gladly take a closer look

**Comment by h55nick** [comment]
Hey Farridav - We are continuing to look into this on our end as well. I'm a little concerned that I've raised this prematurely as it looks like this custom date-selection is relying on the custom template (which doesn't seem to be respected) and without it  the UI doesn't make much sense. I'm going to close this out until I have more confidence that this is indeed a bug with source, vs a strange custom component on our end! Thanks!
