### ISSUE TITLE
Inappropriate warning message for url reversals with app menu item

### ISSUE THREAD

**Issue by paaksing** [farridav/django-jazzmin#232]
Everytime I access a page in the admin, the console will print out this line:
```python
Could not reverse url from <class 'django.contrib.auth.models.Permission'>
```
I have no idea what it is, it doesn't show up any traceback of the "exception (?)", it just keep throwing on each page access, this only happens if I use jazzmin. Thanks

**Comment by TysonRV** [comment]
Mmm.. That means it can't find the url for the Permission's model, which is in django auth. As long as you have `django.contrib.auth` in your `INSTALLED_APPS`, it should work.. so I wonder what happened here, as I'm guessing you didn't replace that model either.

Could you send us your `JAZZMIN_SETTINGS` along with your `INSTALLED_APPS`? Or maybe the whole `settings.py` file, if you don't have anything sensitive there!

**Comment by paaksing** [comment]
I tested various settings, and it has a pattern in it, ***It will always throw "Could not reverse url <class: x>" where x is the last model of the last app in `topmenu_links` settings in `JAZZMIN_SETTINGS`***. Weird thing is, the button to that model actually works without problem ....
```python
JAZZMIN_SETTINGS = {
    "site_title": "My APP Admin",
    "site_header": "MyAPP Administration",
    "site_logo": "myapp/icon.png",
    "welcome_sign": "Welcome MYAPP Admin",
    "copyright": "MYCOMPANY LLC",
    "user_avatar": None,

    "topmenu_links": [
        {"app": "myapp"},
        {"app": "anotherapp"},
        {"app": "auth"}, # <--------- HERE IS THE PERMISSION CLASS
        {"name": "View Site", "url": "https://myapp.com", "new_window": True},

    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    "order_with_respect_to": ["myapp", "anotherapp", "auth"],

    "related_modal_active": False,
    "custom_css": 'myapp/admin.css',
    "custom_js": None,
    "show_ui_builder": False,

    "language_chooser": False,
}
```
App names are replaced by `myapp` and `anotherapp`

**Comment by paaksing** [comment]
If I move `anotherapp` below `auth` then the last model of that app will throw that error ... and so on. I did not modify the `Permission` model

**Comment by farridav** [comment]
This is happening because we are walking through all of the models registered in djangos `auth` app, and trying to get an admin url for each of them. but the `auth` app does not have a url pattern for the `Permission` model, as its managed entirely from the many to many fields.

I am going to look for a nice way to not log a warning in this instance. The purpose of that warning was to let people know if they have included something in their menu that cannot be reversed, but in the case of apps, we extract all models
