### ISSUE TITLE
Add datatable using Javascript/jQuery for all the Django admin tables.

### ISSUE THREAD

**Issue by hamhaingaurav** [farridav/django-jazzmin#233]
I have suffered this issue many times when there are so many columns in my admin panel.

Jazzmin has really great theming, but it is really lacking the advanced and amazing feature like Javascript's datatable.

If a model admin is set to `list_per_page=30` or 50, it becomes really hard to scroll all the way down and then get the scrollbar to see all the columns.

Jazzmin must have this feature.

For Reference:
https://datatables.net/

**Comment by farridav** [comment]
Although datatables its jazzy, and adds a lot of cool functionality to a plain old table i think it would conflict with functionality that django already provides (across all model instances, not just the current page):

- Search
- Pagination
- Sorting
- Limiting

To hook this in properly, we would need to use an api not just DOM elements, this is do-able though its quite a shift from our current integration, as the only configuration change required for jazzmin currently is to add it into `INSTALLED_APPS`, no url patterns, context processors or models required ..

I hope I've explained my rationale fully, thanks for the recommendation
