### ISSUE TITLE
Sidebar Disappears after clicking on Custom admin App

### ISSUE THREAD

**Issue by jamesreinhold** [farridav/django-jazzmin#235]
In my admin.py I created a Custom app for Django admin and here is the code;

Here is the code in my admin.py - https://prnt.sc/w65jlh

After registering the app in the Admin it successfully appears in the sidebar(I have customized the Jazzmin template to my specification) - https://prnt.sc/w65ei8

Now when I click on the app, it opens alright but the other menu disappears. Only the static menu is shown on the page. Like this - https://prnt.sc/w65ffc

I need help on how to make sure the custom app created shows up in the sidebar apps

**Comment by farridav** [comment]
Closing this, I have demonstrated how one might override a changeform template here https://github.com/farridav/django-jazzmin/pull/236 

Let me know on that PR if theres anymore examples I can provide, or assistance i can provide
