### ISSUE TITLE
Select Width for ForeignKey on Admin Change Form

### ISSUE THREAD

**Issue by jonasjahns** [farridav/django-jazzmin#242]
When show a Simple Select for ForeignKey on Admin form the width of the field isn't set right.
As you can see on the test app, the width of the element is set to 163px:
![image](https://user-images.githubusercontent.com/27732499/102929342-2c4e6980-4479-11eb-9832-bee933fd835a.png)
But, it needs to be set to 168px so the whole text can apper in the select widget:
![image](https://user-images.githubusercontent.com/27732499/102929384-4425ed80-4479-11eb-9eb7-e4c5dea2321a.png)

I don't know if its intended to be like this, but, it stated on 2.4.0.

**Comment by farridav** [comment]
Is this happening on master ? I recently set the select2 width option to be "element" in a hope to resolve these issues...

**Comment by SVDouble** [comment]
Yep, I can confirm
I'm facing the same issue
Everything works as expected in the version 2.4.2 though

**Comment by jonasjahns** [comment]
@farridav i'm using the lattest version avaliable
![image](https://user-images.githubusercontent.com/27732499/102996655-3f594c00-4502-11eb-9a09-5c91def29322.png)
The previous prints are from the demo app of jazzmin :)

**Comment by linhnvhicts** [comment]
I'm on jazzmin 2.4.3 and this also happening to alot of the foreign key fields, most of the text are hidden which look really ugly
![Screen Shot 2021-01-08 at 10 24 26 AM](https://user-images.githubusercontent.com/46511495/103970822-b72ea400-519b-11eb-971c-1eaa7ff61f32.png)

**Comment by farridav** [comment]
Sure, I'll give this a try, I tried to reproduce the problem in the demo app with no success, it looked as though allowing the `element` to determine its width would fit all scenarios, but I guess there is some race condition there where the elements width is calculated before the choices are populated.

I'll update with my findings asap

**Comment by jonasjahns** [comment]
@farridav is saw your test in the demo app.
In my browser it's repoducing the error, as you can see bellow:
![image](https://user-images.githubusercontent.com/27732499/104017540-0faf7280-5197-11eb-9040-bfc6d906c26b.png)

**Comment by budlight** [comment]
I am having this same issue. on 2.4.4

Why not just change the design so it goes to max width?  Maybe later add an option to either set it to auto or a width?

```
.select2-container {
    width: 100% !important;
}
```
effectively solves my issue but then wraps the edit and add icons to the next line (but its useable where with auto it is not)


![image](https://user-images.githubusercontent.com/329613/112389131-78e05580-8cb1-11eb-96cd-9b49013df30d.png)

**Comment by SVDouble** [comment]
@farridav
This issue persists on the master branch as well.
What solves it in my case are the following steps:
a) set select2 parameters in the **`change_form.js`** to ([commit](https://github.com/SVDouble/django-jazzmin/commit/c4091fe9e622122d95f6844fee67e552f6771c37)):
`$('select').not(noSelect2).select2({ width: '100%', theme: "classic" });`
It is also important that the theme is specified: without it some elements look really ugly
b) set select2 parameters in the **`change_list.js`** to ([commit](https://github.com/SVDouble/django-jazzmin/commit/ede8892cea0871765fcdbad00afc804cfa1a57b7)):
`$ele.select2({ width: '100%' });`

**Comment by jonasjahns** [comment]
> @farridav
> This issue persists on the master branch as well.
> What solves it in my case are the following steps:
> a) set select2 parameters in the **`change_form.js`** to ([commit](https://github.com/SVDouble/django-jazzmin/commit/c4091fe9e622122d95f6844fee67e552f6771c37)):
> `$('select').not(noSelect2).select2({ width: '100%', theme: "classic" });`
> It is also important that the theme is specified: without it some elements look really ugly
> b) set select2 parameters in the **`change_list.js`** to ([commit](https://github.com/SVDouble/django-jazzmin/commit/ede8892cea0871765fcdbad00afc804cfa1a57b7)):
> `$ele.select2({ width: '100%' });`

Hi SVDouble, i tried this but didn't work out for me!
