### ISSUE TITLE
Select2 min-width needed

### ISSUE THREAD

**Issue by Pijuli** [farridav/django-jazzmin#245]
Hi!
select2 (in many to many fields)  has not any kind of min-width as vDateField, vTimeField (200px), or event inputs that are width 100%, so it appears messed up.

The style comes from .select2-container.min.css that should be overriden to contain min-width=200px 
There's also a style="width: auto;" in the container that should be removed

I don't know if that approach fits you.

**Caption when no item is selected:**
![Captura de 2021-01-15 14-06-44](https://user-images.githubusercontent.com/1220004/104730833-05631a80-573b-11eb-8a1e-ea17aadcc2f7.png)

**Caption when item is selected:**
![Captura de 2021-01-15 14-07-08](https://user-images.githubusercontent.com/1220004/104730835-05fbb100-573b-11eb-8b11-824609782144.png)

**Comment by rmaranhao** [comment]
May help: The width is OK on Firefox. I can only reproduce this in Chrome.

**Comment by farridav** [comment]
I've had a lot of back and forth width the Select2 width, I'm surprised that I've had so many problems with it, I always considered it a fairly simple requirement, just adapt to the width of the longest option element...

But for some reason every option in select2's API seems to have adverse results for someone, and I'm rarely ever able to reproduce the issue (possibly a race condition)

The Dom elements used in the select appear quite complex, I've had difficulty applying CSS rules to it that make a difference, but I'm happy to give this another shot.

Do you have a way for me to reproduce failure ? So I can toy with the Dom elements and Select2 API again ?

**Comment by farridav** [comment]
I admit I have not tested this with a select that has no option selected, so I'll try that first, and see if the min width option has no adverse affects for other use cases

**Comment by Pijuli** [comment]
Sorry, I've been out for the whole weekend. thank you very much for the quick fix. I'm gonna give it a try.
Hope no wild sideeffects appear :)
