### ISSUE TITLE
Auth User Error on Admin Login

### ISSUE THREAD

**Issue by jameswinegar** [farridav/django-jazzmin#247]
The default Django admin template has a nice UX feature where it will let you know if you're trying to connect to the admin and do not have staff or superuser permissions. Jazzmin doesn't seem to have this and it would be nice.

<img width="412" alt="Screen Shot 2021-01-16 at 11 22 44 AM" src="https://user-images.githubusercontent.com/8434889/104818488-972b6000-57ed-11eb-8611-d1702aebcd03.png">

**Comment by farridav** [comment]
How interesting, yes we should definitely pass this through, if you have time to have a crack at it, I'll gladly review the pull request.

Otherwise I'll get to this as soon as I can .

Thanks for flagging
