### ISSUE TITLE
Bug that prevents dark-themes from being applied.

### ISSUE THREAD

**Issue by Max77I7** [farridav/django-jazzmin#255]
I think I found a bug.

The line 283 in the file jazzmin\settings.py:
`        "dark_mode_theme": {"name": dark_mode_theme, "src": static(THEMES[theme])},
`
need to be replaced with:
`        "dark_mode_theme": {"name": dark_mode_theme, "src": static(THEMES[dark_mode_theme])},
`

The problem is that in the current version there is no case where a dark-theme stylesheet can be loaded.

**Comment by hwalinga** [comment]
I think you are correct, so I opened a PR.

**Comment by farridav** [comment]
Closed by https://github.com/farridav/django-jazzmin/pull/257
