### ISSUE TITLE
Problem with map on tabbed model view with Point

### ISSUE THREAD

**Issue by Fasther** [farridav/django-jazzmin#265]
Hello,
first of all, thank you for all work that was put into this project!

We found a problem with `PointField` in Admin.

### Prerequisites

- Django: 3.1.7
- Jazzmin: 2.4.4
- Python: 3.8
- Chrome: 88.0.4324.190

## What is the problem:
When you use tabbed view together with `PointField `, not on the first page, the map will be blank till you make any screen resize or zoom:
![image](https://user-images.githubusercontent.com/30392053/110997903-59c2f900-837e-11eb-9fe7-811c6eeeaea8.png)
When you resize the window/zoom in/out, the map appears!
![image](https://user-images.githubusercontent.com/30392053/110998028-81b25c80-837e-11eb-87be-733771d092d1.png)

**What works:**
- Not tabbed view
- Map on the first tab

**Additional info:**
HTML when map is not visible:
`<canvas class="ol-unselectable" style="width: 100%; height: 100%; display: none;"></canvas>`   
HTML after page resized:
`<canvas class="ol-unselectable" style="width: 100%; height: 100%;" width="600" height="400"></canvas>`

## How to reproduce:
**You can use this repo made just for this: https://github.com/Fasther/jazzmin-point-bug/tree/master/jazzmintest/testj**
Needs Django, Jazzmin and PostGIS installed...

_or..._
**Step by step:**
1. Create a blank Django project and app
2. Define model with `PointField` and some other field (doesn't matter)
3. Create admin, where you will place the map on the second group/tab
4. In admin after you switch to this tab the map will be blank

**Comment by farridav** [comment]
Interesting, it must be that the map is rendered out into an invisible dom element, and theres some sort of event that sets it to `display none` , or the inverse, theres supposed to be an event firing that sets its display to visible.

I need to find some time to reproduce (thanks for putting up the repo), at first glance it looks liek we can address this with one of the following (in order of preference):

1. Find out what event the maps JS is supposed to fire, and trigger that once tabs are loaded 
2. Fix it with CSS, e.g `canvas.ol-unselectable { display: block !important }`
3. Fix it with JS e.g `jQuery('canvas.ol-unselectable').show();`

**Comment by kainbacher** [comment]
A solution for this issue is to trigger `window.dispatchEvent(new Event('resize'));` after clicking a tab.
