### ISSUE TITLE
Filter disappears

### ISSUE THREAD

**Issue by sunnysid3up** [farridav/django-jazzmin#269]
I use both search and and filters for a model, but the filters are gone when I use Jazzmin. There's only a search bar on top right corner and an icon on top of the search bar.

![image](https://user-images.githubusercontent.com/17933228/112422042-9c6bd480-8d73-11eb-8a9b-5a13e08411e1.png)

--
django version: 3.0.13
django-jazzmin version 2.4.4

**Comment by farridav** [comment]
Any tips on how to reproduce this ? in our demo app we have search and filters, and it renders fine, (see https://django-jazzmin.herokuapp.com/en-gb/admin/books/book/) 

If your able to help us reproduce this in the demo app, we will take a look at it ..

**Comment by sunnysid3up** [comment]
Hi, thanks for sharing the demo. It started working again after I removed `DIRS` in TEMPLATES in Django settings.

```python
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            # ...
        },
    },
]
```
