### ISSUE TITLE
Set order of tabs in change view when inserting inlines

### ISSUE THREAD

**Issue by frankpachar** [farridav/django-jazzmin#275]
First of all I want to leave my sincere congratulations to farridav for such a wonderful project.

I have the following inlines:
inlines = (TsAccessoryRegisterInline, TsStatusInline, TsSoftwareLicenseInline, TsContactInline,)
In addition to the data of the main form, but all the inlines are located in tabs after the data of the main form and what I need is to be able to put them in order by mixing with the fields of the main form.
In django-suit you could achieve this with the following code:
suit_form_tabs = (
         ('serviceorder', 'Service order',),
         ('equipment', 'Equipment',),
          ('budget', 'Budget',),
         ('status', 'Status change',),
         ('contact', 'Contacts',),
         ('technical_report', 'Technical report',),
          ('deliver', 'Delivery',),
          ('system', 'System'),
     )
where I could indicate, apart from the order of the inlines, in which tab the inline would be shown, I would like to know how I can achieve that in django-jazzmin

![issue fw](https://user-images.githubusercontent.com/81596496/112916100-7de44100-90c5-11eb-8cbd-5759edc71f3d.png)

**Comment by farridav** [comment]
I have got something into `master` that allows you order tabs, please give it a go, and let me know if it helps with your use case (https://github.com/farridav/django-jazzmin/blob/master/tests/test_app/library/books/admin.py#L46)

**Comment by frankpachar** [comment]
Thanks for your help, if you ever visit Ecuador I would like to be your host.
You can now order the tabs, however in a future version it would be important to be able to put more than one group of fields in the same tab, as sections, and with the inlines type master detail.
It would also be interesting to be able to establish which tab is selected by default, which I have achieved in the following javascript code:
//set default tab
//$('a[href = "#name-tab"]')[0].click();

**Comment by farridav** [comment]
No worries, you can achieve most of this using fieldsets in an admin class https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets

The only tricky thing is ordering inlines, or mixing them in with other fieldsets, there is a ticket in Django for supporting this https://code.djangoproject.com/ticket/4848

Maybe a future change to this would be to fall back on the Django admin fieldsets API, and find a way to support inlines as a field type or section

**Comment by frankpachar** [comment]
Thanks for your support I will keep trying

**Comment by farridav** [comment]
Closing this as resolved in master, feel free to raise new tickets for more specific functionality
