### ISSUE TITLE
When number of records exceeds 500 or so, pagination throws an error. Cannot concat int and str.

### ISSUE THREAD

**Issue by jaishankarh** [farridav/django-jazzmin#281]
The following is the error thrown.

Request Method: | GET
-- | --
http://localhost:8000/admin/core/location/?p=4
3.2
TypeError
can only concatenate str (not "int") to str
/home/jaishankar/.envs/way2Env/lib/python3.8/site-packages/django/utils/functional.py, line 180, in __add__
/home/jaishankar/.envs/way2Env/bin/python
3.8.5

I figured that the problem lies in line 210 of jazzmin/templatetags/jazzmin.py, an extra condition needs to be handled. I have marked the condition in bold.

`@register.simple_tag
def jazzmin_paginator_number(cl: ChangeList, i: int) -> SafeText:
    """
    Generate an individual page index link in a paginated list.
    """
    if i == ".":
        html_str = """
            <li class="page-item">
            <a class="page-link" href="javascript:void(0);" data-dt-idx="3" tabindex="0">…</a>
            </li>
        """

    elif i == cl.page_num:
        html_str = """
            <li class="page-item active">
            <a class="page-link" href="javascript:void(0);" data-dt-idx="3" tabindex="0">{num}
            </a>
            </li>
        """.format(
            num=i + 1
        )
    elif i == '…':
        html_str = """
            <li class="page-item">
            <a class="page-link" href="javascript:void(0);" data-dt-idx="3" tabindex="0">… </a>
            </li>
        """
    else:
        print(i)
        query_string = cl.get_query_string({PAGE_VAR: i})
        end = mark_safe("end" if i == cl.paginator.num_pages - 1 else "")
        html_str = """
            <li class="page-item">
            <a href="{query_string}" class="page-link {end}" data-dt-idx="3" tabindex="0">{num}</a>
            </li>
        """.format(
            num=i + 1, query_string=query_string, end=end
        )

    return format_html(html_str)`

**Comment by danlamanna** [comment]
This is also happening to me as of Django 3.2 (not on 3.1).

**Comment by farridav** [comment]
Should be an easy fix, anyone want to have a shot at it ? If not I will  try and get to it later on in the week..
