### ISSUE TITLE
Possibly mismatched permission

### ISSUE THREAD

**Issue by sondrelg** [farridav/django-jazzmin#283]
Hi! 

First of all thanks for maintaining this package - it's really good 👏 

We recently decided to try and implement `django-jazzmin` in one of our projects, and after the switch we got a report from a user that they could no longer see the `History` button on a model detail views. After looking through the code I've managed to boil it down to [this line of code](https://github.com/farridav/django-jazzmin/blob/master/jazzmin/templates/admin/solo/change_form.html#L14). Seems you need one of two permissions or the button is hidden.

Fixing this was easy enough, but after toggling off the theme, I see that this doesn't in fact match the Django admin. I tried finding the Django equivalent, and think [this](https://github.com/django/django/blob/main/django/contrib/admin/templates/admin/change_form_object_tools.html#L4) is the original link. 

I suppose this *might* be intentional, but in the case that it isn't I thought I'd let you know 🙂

**Comment by farridav** [comment]
The plan is to match Django in all areas possible, so if the button is showing in Django, but not with jazzmin, then there is a fix needed on our side.

If you wanted to submit a PR for this, I'll take a look, otherwise I hope to do some bits towards the end of the week.

Thanks for reporting :)

**Comment by farridav** [comment]
No worries, I'll update this ticket once I have it resolved

**Comment by sondrelg** [comment]
Actually I guess the fix is easy enough to set up for you, so I opened a quick PR 🙂
