### ISSUE TITLE
More customization on logo and icon

### ISSUE THREAD

**Issue by GoodStuff11** [farridav/django-jazzmin#286]
Hello, good work on the package! I have some suggestions regarding customization of logos and icons, because it's lacking. 

As of now, the only way to change to logo is with the site_logo variable, and that will change both the icon and the logo, but allowing for no further customization. Often companies have two different images for their icon and logo, it would be nice if jazzmin allowed for this.

In addition, the logo image is of the class `branch-image img-circle elevation-3` which looks really bad for non-circular logos. For my purposes, having the class as just `branch-image` would be good, but in general, jazzmin should allow for more customization in this.

**Comment by farridav** [comment]
These are valid observations and good ideas, I'll have a crack at it this weekend, as I have some other bits to do on Jazzmin :)
