### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by matthewelwell** [farridav/django-jazzmin#289]
Hi there, 

I have noticed a couple of issues with the pagination: 

(1) The links at the bottom of the page are offset by 1, so the first page is actually labelled as '2' rather than 1. 
(2) The application throws an exception once more than 1000 records are created (or more specifically, more than 10 pages are needed). 

A snippet of the stack trace: 

```python
  File "/Users/matthewelwell/projects/sandbox/jazzmin-test/.venv/lib/python3.9/site-packages/jazzmin/templatetags/jazzmin.py", line 210, in jazzmin_paginator_number
    num=i + 1, query_string=query_string, end=end
  File "/Users/matthewelwell/projects/sandbox/jazzmin-test/.venv/lib/python3.9/site-packages/django/utils/functional.py", line 180, in __add__
    return self.__cast() + other
  TypeError: can only concatenate str (not "int") to str
```

It seems to be once the number of pages exceeds the maximum possible to display and hence an ellipsis is needed, the exception is then thrown since `i` in `jazzmin_paginator_number` is set to this ellipsis value for one of the links it tries to render.

I've managed to recreate the issue with a simple application including a single model and I've just created 1001 skeleton models.

```python
# models.py
from django.db import models

class MyModel(models.Model):
    name = models.CharField(max_length=100)
```

```python
# admin.py

from django.contrib import admin
from .models import MyModel


@admin.register(MyModel)
class MyModelAdmin(admin.ModelAdmin):
    pass
```

Thanks,
Matt

**Comment by matthewelwell** [comment]
Ah! I see the second issue looks like it's probably been resolved in your latest commit [here](https://github.com/farridav/django-jazzmin/commit/0c6eccb185a6d337f7e224680497a37da9b6f741).

The first issue I believe still remains. I think it's just a case of changing the references to `i + 1` to just `i` but I'm not sure if there was a reason you're using `i + 1` ?

**Comment by matthewelwell** [comment]
Hi @farridav, would you consider releasing the latest code to pypi so that I can update on my side to fix issue 2 above 🙏 ?

**Comment by farridav** [comment]
Yeah makes sense, I've also merged in your offset PR, I've put the release out now (2.4.6) if both of these issues are resolved, feel free to close the issue

**Comment by matthewelwell** [comment]
Looks good, thanks @farridav.
