### ISSUE TITLE
Django 2.0.x incompatibility

### ISSUE THREAD

**Issue by lchojnacki** [farridav/django-jazzmin#291]
Hi guys,

I noticed that `django-jazzmin` is not compatible with Django 2.0.x. You're using the `change_list_object_tools` and `change_form_object_tools` templatetags that are not available until Django 2.1a1: https://github.com/django/django/commit/5cc28dc752c3ae78456bb835c3ba195489fc26d7

It would be nice if you could be compatible with Django 2.0.x. Otherwise, please change the project requirements to `django>=2.1`.

Thanks,
Łukasz

**Comment by farridav** [comment]
I see, I hadn't realised, and thought we had Django compatibility proven through the test suite.

First step, we need to get the tests to fail, then we need to look at much work is involved in adding and maintaining that compatibility layer, then make the call in wether to bump the Django requirements or implement the patch.

Time wise, I'm stretched at the moment, I'll gladly review any PRs for this, failing that, I'll try to get to it this weekend amongst some of the other items.

**Comment by lchojnacki** [comment]
Your test suite did not test minor versions of Django. I changed that in the PR above and it was enough for the tests to fail.

**Comment by farridav** [comment]
Amazing work, thanks for kicking this off, I'll think about a compatability layer here, and we will see how plausible/ugly/maintainable it is, ideas and contributions are welcome

**Comment by lchojnacki** [comment]
As nothing is happening here, I removed incompatible Django versions from `pyproject.toml`.
