### ISSUE TITLE
admindoc: 'WSGIRequest' object has no attribute 'current_app' at jazzmin.py line 136

### ISSUE THREAD

**Issue by 1171000408** [farridav/django-jazzmin#297]
Got an exception when using admin doc at Django 3.2
\venv\lib\site-packages\jazzmin\templatetags\jazzmin.py, line 136

` admin_site = {x.name: x for x in all_sites}.get(request.current_app)`

this line raised an exception of that 'WSGIRequest' object has no attribute 'current_app'

local vars

> request 	
> 
> <WSGIRequest: GET '/admin/doc/'>
> 
> settings 	
> 
> {'changeform_format': 'vertical_tabs',
>  'changeform_format_overrides': {'auth.group': 'vertical_tabs',
>                                  'auth.user': 'collapsible'},
>  'copyright': XXX',
>  'custom_css': None,
>  'custom_js': None,
>  'custom_links': {},
>  'default_icon_children': 'fas fa-circle',
>  'default_icon_parents': 'fas fa-chevron-circle-right',
>  'hide_apps': [],
>  'hide_models': [],
>  'icons': {'auth': 'fas fa-users-cog',
>            'auth.group': 'fas fa-users',
>            'auth.user': 'fas fa-user'},
>  'language_chooser': False,
>  'navigation_expanded': False,
>  'order_with_respect_to': ['auth'],
>  'related_modal_active': True,
>  'search_model': 'auth.User',
>  'search_name': '用户',
>  'search_url': '/admin/auth/user/',
>  'show_sidebar': True,
>  'show_ui_builder': True,
>  'site_header': 'XXX',
>  'site_logo': 'logo.png',
>  'site_title': 'XXX',
>  'topmenu_links': [{'name': '首页',
>                     'permissions': ['auth.view_user'],
>                     'url': 'admin:index'},
>                    {'name': 'Support',
>                     'new_window': True,
>                     'url': 'sample@sample.com/'},
>                    {'model': 'auth.User'},
>                    {'app': ''}],
>  'user_avatar': 'avatar',
>  'usermenu_links': [{'name': 'Support',
>                      'new_window': True,
>                      'url': 'sample@sample.com/'},
>                     {'model': 'auth.user'}],
>  'welcome_sign': 'Welcome'}
> 

environments

> python 3.8
> django 3.2
> docutils 0.17
> jazzmin 2.4.6

confirmed that the 'admin/doc/' path is annouced before 'admin/' path
confirmed that https://django-jazzmin.herokuapp.com/admin/doc/ does have problem (Server error 500)

**Comment by farridav** [comment]
Good spot ! And clearly something we could have a functional test for..

I'll hotfix this tomorrow and close off this issue when released to pypi

**Comment by 1171000408** [comment]
More interesting thing.
Something wrong with django 3.1.2, if you put "admin/doc" path before "admin" path, jazzmin works
Ok.
