### ISSUE TITLE
List view pagination arrows not working

### ISSUE THREAD

**Issue by palpalpa** [farridav/django-jazzmin#299]
how can i add pagination arrows in my project
pagination arrows are not working ,pls anyone can suggest me how can i do ?

![Screenshot from 2021-04-23 12-48-42](https://user-images.githubusercontent.com/82817619/115835964-8b76b780-a434-11eb-8994-e6f71e3f40d4.png)

**Comment by farridav** [comment]
Can you send a screenshot of the part you are referring to ? 

Are you referring to the list view, and if so, where are you trying to put the arrows ?

**Comment by palpalpa** [comment]
![Screenshot from 2021-04-23 12-48-42](https://user-images.githubusercontent.com/82817619/115834463-e27b8d00-a432-11eb-9293-dfcbc4635f6c.png)

**Comment by palpalpa** [comment]
right and left arrows are not working

**Comment by palpalpa** [comment]
> right and left arrows are not working

**Comment by farridav** [comment]
Ok, now I understand, I'll update the issue to reflect the problem.

Those arrows should be working, this is something I hope to get to this week.

**Comment by palpalpa** [comment]
have you fixed the paginatons arrows bugs

**Comment by farridav** [comment]
It's in master now yes, I've not yet released it to pypi though

**Comment by palpalpa** [comment]
![Screenshot from 2021-04-23 19-53-00](https://user-images.githubusercontent.com/82817619/115885710-d4972d80-a46d-11eb-9dc9-3fa57d2c3261.png)

Actions dropdown looks like ("-------"),
nstead of "-------", add text as "Select Action"

how can i do this?? pls suggest me

**Comment by palpalpa** [comment]
![Screenshot from 2021-04-23 19-53-00](https://user-images.githubusercontent.com/82817619/115886260-5c7d3780-a46e-11eb-99be-e5d4bd9ab650.png)

**Comment by farridav** [comment]
I'm not sure what you are referring to in afraid, perhaps you can provide a screen shot again ? For me in the demo app, the unselected action is rendering as expected.. 

https://django-jazzmin.herokuapp.com/en-gb/admin/loans/library/

User: test@test.com
Pass: test

**Comment by palpalpa** [comment]
search and filter funtion are not working simultaneously

**Comment by palpalpa** [comment]
you have released pagination working arrows part to pypi though

**Comment by farridav** [comment]
The pagination links have not yet been released to pypi, but they are on master branch.

We try to roll up a few more changes before doing a release.

I aim to get a release out soon, I've just got to go through some of the other priority items and see if I can get them in the same release
