### ISSUE TITLE
'WSGIRequest' object has no attribute 'current_app' , when calling logout 

### ISSUE THREAD

**Issue by ab-smith** [farridav/django-jazzmin#308]
Hi,
in my app I'm calling {% url 'logout' %} at some point and I get this error.
it looks related to this in the Django doc: https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#adding-views-to-admin-sites 
Logging-out from the admin is working fine.
Thank you,

**Comment by farridav** [comment]
his should be resolved with the latest release 2.4.7 please confirm if thats not the case

**Comment by ab-smith** [comment]
yes, it is fixed now, thank you!
