### ISSUE TITLE
Problem with Localization

### ISSUE THREAD

**Issue by metehankutlu** [farridav/django-jazzmin#311]
Hi

I recently discovered Jazzmin and started to use. I'm having an issue with some translations. In my project there is only one language which is Turkish and most of the things get translated very well but there are some missing ones like Dashboard, See Profile, Actions etc. How can i translate them? I don't know if it's right to ask here but I believe they came with Jazzmin.

**Comment by farridav** [comment]
Hi there, adding new translations should be easy to do, I've added some basic documentation here https://django-jazzmin.readthedocs.io/development/#translations

You should be able to see some translations already in the project, there are not many strings that jazzmin introduces, the vast majority of translations come from djangos comprehensive language support.

Feel free to copy an existing language folder and add Turkish in if you like, I'm sure our Turkish users would appreciate it :)

**Comment by metehankutlu** [comment]
Oh, I guess I missed it in the docs. Thanks for the answer
