### ISSUE TITLE
Outside <script> tags

### ISSUE THREAD

**Issue by lightninglu10** [farridav/django-jazzmin#317]
Is there anyway to add custom <script> tags? There's some outside JS that we'd like to include in jazzmin.

**Comment by farridav** [comment]
Sure, its no different from how you would normally do it with a django template, overriding one of the base templates, and making use of one of the following blocks:

```
{% block extrastyle %} {% endblock %}
{% block extrahead %} {% endblock %}
{% block extrajs %}{% endblock %}
```
 
Here is a working example: https://github.com/farridav/django-jazzmin/commit/94defc6f6c6af084473b56c77d9d698c2c4fa74c

Hope that helps..
