### ISSUE TITLE
'str' object is not callable after adding jazzmin with coustom user model

### ISSUE THREAD

**Issue by Druvo** [farridav/django-jazzmin#324]
![Screenshot_2](https://user-images.githubusercontent.com/38050615/124507624-f9097180-ddef-11eb-8767-a27cdb112b7c.png)

**Comment by farridav** [comment]
Interesting, so your user object is a string somehow, I'll see if I can reproduce this tomorrow,  though even with a custom user module I'd still expect a lazy user object..

**Comment by Druvo** [comment]
# Here are the custom UserManager and User model please let me know if I am doing something wrong

class UserManager(BaseUserManager):
    def create_user(self, phone, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not phone:
            raise ValueError('Users must have an email address')

        user = self.model(
            phone=phone
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, phone, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            phone,
            password=password,
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            phone,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    # You can create Role model separately and add ManyToMany if user has more than one role
    email = models.EmailField(
        _('Email Address'), max_length=255, unique=True, blank=False, null=True
    )

    phone = models.CharField(
        _('Mobile Phone'), max_length=12, blank=True, null=True, unique=True,
        validators=[RegexValidator(r'^[\d]{10,12}$',
                                   message='Format (ex: 0123456789)'
                                   )])

    first_name = models.CharField(
        _('First Name'), max_length=255, blank=True, null=True
    )

    last_name = models.CharField(
        _('Last Name'), max_length=255, blank=True, null=True
    )

    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []  # Phone & Password are required by default.

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def __str__(self):
        return self.phone

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission? yes."
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`? yes."
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin
    
    @property
    def get_all_permissions(self, obj=None):
        return ""

**Comment by farridav** [comment]
Your get_all_permissions method is using the property decorator .. I'm not sure it should be, also it's returning a string, it's meant to return a list of permission strings..

**Comment by Druvo** [comment]
yes that was the problem i remove the line below 
@property
    def get_all_permissions(self, obj=None):
        return ""
