### ISSUE TITLE
Add credits with links to django-admin-interface as you have COMPLETELY COPIED the related modal js.

### ISSUE THREAD

**Issue by fabiocaccamo** [farridav/django-jazzmin#326]
As you have completely copied the JavaScript for the modal from [django-admin-interface](https://github.com/fabiocaccamo/django-admin-interface), it would be nice and correct to mention the source of the code.

This is the JavaScript:

**`popup_response.js`**
- `django-admin-interface` source: https://github.com/fabiocaccamo/django-admin-interface/blob/master/admin_interface/static/admin/js/popup_response.js
- `django-jazzmin` copy: https://github.com/farridav/django-jazzmin/blob/master/jazzmin/static/admin/js/popup_response.js

**`cancel.js`**
- `django-admin-interface` source: https://github.com/fabiocaccamo/django-admin-interface/blob/master/admin_interface/static/admin/js/cancel.js
- `django-jazzmin` copy: https://github.com/farridav/django-jazzmin/blob/master/jazzmin/static/admin/js/cancel.js

**Comment by farridav** [comment]
Apologies, this was implemented by a contributor who had said it was *heavily inspired* by your work https://github.com/farridav/django-jazzmin/pull/187

I hadnt realised it was copied verbatim.

We have a few bugs with it on mobile, and have disabled its use by default, but people can opt to use it.

Ill gladly credit you in the project documentation, and perhaps check if theres a newer version we can pull in.

TODO: 

- [ ] Add credit and link to project documentation

Thanks for your great work.

**Comment by fabiocaccamo** [comment]
@farridav thank you very much!
