### ISSUE TITLE
Font awesome custom icons don't render

### ISSUE THREAD

**Issue by ahmedelfateh** [farridav/django-jazzmin#359]
my setting 👇
`"icons": {
        "users.User": "fas fa-users-cog",
        "users.SnackatUser": "fas fa-user",
        "users.SupplierUser": "fas fa-users",
        "users.ShadowUser": "fas fa-users",
        "users.FeedBack": "far fa-comment-alt",
        "users.Role": "fas fa-book-open",
        "configs.Config": "fas fa-sliders-h",
        "tasks.TaskLog": "fas fa-tasks",
        "tasks.CronObject": "fas fa-th",
        .
        .
    }`
I deploy on AWS Elastic Beanstalk.
how it shows 👇
![Screen Shot 2021-12-29 at 10 03 11 PM](https://user-images.githubusercontent.com/2853179/147699378-fe35dee6-ef7f-4766-9cc2-a132a7ffc6ca.png)

**Comment by AndrejGorodnij** [comment]
Looks more like "unicode" problem, not Jazzmin.

**Comment by ahmedelfateh** [comment]
@AndrejGorodnij 
thank you for you answer, any hit how to fix this.

**Comment by AndrejGorodnij** [comment]
> @AndrejGorodnij 
> thank you for your answer, any hit how to fix this.

You can try to detect conflicts between js-libraries, for example.

From Font Awesome docs - https://fontawesome.com/v5.15/how-to-use/on-the-web/other-topics/conflict-detection

I use Jazzmin on 2 sites in last month, and hadn't any artefacts. Do you use FontAwesome on your FrontEnd? Do you use custom Django Admin templates?

**Comment by ahmedelfateh** [comment]
I am using frontends with APIs and it is working fine, and no custom templates.
the thing that it is running well on the local.

**Comment by ahmedelfateh** [comment]
> 

it seems that this will work, I will try this and tell you it is working.

**Comment by ahmedelfateh** [comment]
@AndrejGorodnij 
Great, it worked well.
 thanks for your help!
