### ISSUE TITLE
Can´t see user menu django-jazzmin

### ISSUE THREAD

**Issue by PatricioHenderson** [farridav/django-jazzmin#372]
Hello I am having an issue with django-jazzmin. I can´t see the usermenu on the navbar I mean is there but even though i change the navbar colour it can't bee seen
![image](https://user-images.githubusercontent.com/72527088/153043841-ed17bb39-f9da-4447-89c4-0ef17a2c6355.png)
![image](https://user-images.githubusercontent.com/72527088/153043943-536579be-5d4d-4898-b26f-5ff87a8c4413.png)

**Comment by farridav** [comment]
Are you using some custom css ? this doesnt appear to be a problem in a standard jazzmin installation .. see https://django-jazzmin.herokuapp.com/en-gb/admin/ for reference ..

**Comment by PatricioHenderson** [comment]
Hi @farridav Thanks for your time. You are right.
