### ISSUE TITLE
StackedInline show 3 new elements on edit 

### ISSUE THREAD

**Issue by VictorValar** [farridav/django-jazzmin#380]
StackedInline shows 3 newly created objects when you try to edit it. 

![image](https://user-images.githubusercontent.com/54588980/158302856-5d0498f5-f151-41a7-919b-4b652df21643.png)

**Comment by MathiasKowoll** [comment]
You should look into the extra feature on admin.py

**Comment by farridav** [comment]
As @MathiasKowoll mentioned, this is something that django controls, if you would like to control the number of additional inlines that are generated, please add the `extra = 1` to your inline model admin class, see https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#django.contrib.admin.InlineModelAdmin.extra for more info
