### ISSUE TITLE
Related objects select doesn't enable the edit/delete icons

### ISSUE THREAD

**Issue by dekomote** [farridav/django-jazzmin#384]
- Jazzmin version: master, 2.4.9
- Parts affected: All pages with related object selects and inline buttons for edit/delete
- Steps to reproduce: Have an admin for a model with a foreign key, select should appear in the form with 3 buttons next to it for editing adding and deletion. When nothing is selected, only the add button should work. When an object is selected in the select, all 3 buttons should work. This is not the case here, the edit and delete buttons aren't enabled.

In forms with related object selects, if one has permissions to edit/delete the related objects, one can see buttons for that, which, when clicked, opens a popup to edit/delete the object in question.
Those buttons are disabled when there's nothing selected in the related objects select, and they are immediately enabled when one is selected. This is django behavior.
This, however, doesn't work on jazzmin because select2 for some reason unbinds the change event on the select.

I have a PR that fixes this - it rebinds the event after applying select2 #383

**Comment by farridav** [comment]
Closed by https://github.com/farridav/django-jazzmin/pull/383
