### ISSUE TITLE
Django 4.0 Admin Docs is not styled

### ISSUE THREAD

**Issue by PrynsTag** [farridav/django-jazzmin#391]
I am using Django 4.0.2 and installing the [Admin Docs](https://docs.djangoproject.com/en/4.0/ref/contrib/admin/admindocs/) currently has a breaking UI. 

See image bellow:

![image](https://user-images.githubusercontent.com/56314705/161347643-8c526d53-03dc-4b77-8c55-f3f23153faca.png) 

There is an github issue #44 which suggests that is not the desired outcome and also Django 4.0 is supported #366 under this issue.

**Comment by PrynsTag** [comment]
Solved! django.contrib.admindocs must be underneath `jazzmin` app to apply django-jazzmin styles.

```python
INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.admindocs',
    [...]
]
```

Perhaps this should also be in the documentation @farridav?

**Comment by farridav** [comment]
Sure, i can add this into the docs to avoid confusion
