### ISSUE TITLE
Hide Sidebar

### ISSUE THREAD

**Issue by mshs013** [farridav/django-jazzmin#445]
Afrer setting "show_sidebar": False, in my settings.py it hides side bar but it shows white
![Site-administration-OCMS-ERP](https://user-images.githubusercontent.com/10936073/194708309-27db38e5-cc2a-4314-a70e-97885db78700.png)
Please help to fix this.

**Comment by yogeshdmca** [comment]
It's cache issue. 
1. restart your dev server.
2. clear the cache  or hard reload the page. 
Hopefully it will work.

**Comment by mshs013** [comment]
> It's cache issue.
> 
>     1. restart your dev server.
> 
>     2. clear the cache  or hard reload the page.
>        Hopefully it will work.
>        if not work then you have to edit conf and css like this
> 
>     3. create a css file(admin-theme.css) in inside static folder and write
>        `@media (min-width: 768px) { body.no-sidebar .content-wrapper, body.no-sidebar .main-footer, body.no-sidebar .main-header { margin-left: 0 !important; } }`
> 
>     4. you need to add custom_css in JAZZMIN_SETTINGS.  like this
>        `"custom_css":  "assets/css/admin-theme.css",`   you can check your path.
> 
>     5. restart  local dev server and reload your page.

Thank you. custom css working fine.
