### ISSUE TITLE
python manage.py collectstatic - error with jazzmin.

### ISSUE THREAD

**Issue by willianmascimiano** [farridav/django-jazzmin#465]
If i install in settings.py the jazzmin moodule, the system will crash on collectstatic command.

if i use the original django-admin interface the collectstatic command works

> The CSS file 'vendor/bootswatch/default/bootstrap.min.css' references a file which could not be found:
  vendor/bootswatch/default/bootstrap.min.css.map. Please check the URL references in this CSS file, particularly any relative paths which might be pointing to the wrong location.

**Comment by willianmascimiano** [comment]
Please ignore.
I've checked and remove unused packages, and works.

**Comment by johncronan** [comment]
It is the same issue as dealt with by the DRF project, here: https://github.com/encode/django-rest-framework/issues/8587

Apparently the Django 4.1 changes to static files cause this issue with references to missing source maps. Here's the reference: https://github.com/farridav/django-jazzmin/blob/6d6429ab241c84322d5c99389f4fed7b5204b5ff/jazzmin/static/vendor/bootswatch/default/bootstrap.min.css#L7

**Comment by johncronan** [comment]
@farridav, easy fix here. We gotta remove that line, or provide the source map.

**Comment by leandrodesouzadev** [comment]
Is there any plans to release a new version with this change?
The 2.6.0 release (latest) doesn't contain this change.

**Comment by shywn-mrk** [comment]
I would be more than happy to see the new release that contains those changes.

**Comment by shywn-mrk** [comment]
I would be more than happy to see the new release that contains those changes.
@farridav
