### ISSUE TITLE
Responsive UI

### ISSUE THREAD

**Issue by neowenshun** [farridav/django-jazzmin#49]
Hello thanks so much for your hardwork , it has made my django admin look more modern and 'jazzy'. Apart from that , i have been fiddling around with it and realize that certain portions of the template is not responsive , for example , the breadcrumb will overlap with the 'dashboard' title when changed to mobile mode and in the 'ipad' mode the actions menu seems cluttered. Is there a way to override these?

**Comment by farridav** [comment]
Yes you can override with custom CSS/JS (See https://django-jazzmin.readthedocs.io/configuration/#ui-tweaks)

Though if there is a change you want to put up a small PR for, we can get it in the project (See https://django-jazzmin.readthedocs.io/development/ for getting setup and contributing)
