### ISSUE TITLE
UI customizer does not show up in the admin page

### ISSUE THREAD

**Issue by neowenshun** [farridav/django-jazzmin#50]
Hey! I have tried using the UI customizer however it does not seem to be working.

`
JAZZMIN_SETTINGS = {
    'show_ui_builder': True,
    # title of the window
    'site_title': 'Nobo CRM Systems',

    # Title on the login screen
    'site_header': 'Nobo Administration',

    # Welcome text on the login screen
    'welcome_sign': 'Welcome',

    # Copyright on the footer
    'copyright': 'Nobo Ltd',

    # The model admin to search from the search bar, search bar omitted if excluded
    'search_model': 'auth.User',

    # Field name on user model that contains avatar image
    'user_avatar': None,

    # Links to put along the top menu
    'topmenu_links': [

        # Url that gets reversed (Permissions can be added)
        {'name': 'Home',  'url': 'admin:index', 'permissions': ['auth.view_user']},

        # external url that opens in a new window (Permissions can be added)
        {'name': 'Support', 'url': 'https://github.com/farridav/django-jazzmin/issues', 'new_window': True},

        # model admin to link to (Permissions checked against model)
        {'model': 'auth.User'},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {'app': 'sales'},
    ],

    # Whether to display the side menu
    'show_sidebar': False,

    # Whether to aut expand the menu
    'navigation_expanded': True,

    # Hide these apps when generating side menu e.g (auth)
    'hide_apps': ['river'],

    # Hide these models when generating side menu (e.g auth.user)
    'hide_models': [],

    # Custom icons per model in the side menu See https://www.fontawesomecheatsheet.com/font-awesome-cheatsheet-5x/
    # for a list of icon classes
    'icons': {
        'auth.user': 'fa-user',
    }
}`

This is my code

**Comment by farridav** [comment]
Im afraid the UI Builder feature has not been released to pypi yet, it should be there in about 30 mins, ive just got to get my PR in https://github.com/farridav/django-jazzmin/pull/51 then ill do a release, ill update this thread once done ..

**Comment by farridav** [comment]
Version 2.1.1 has no been released to pypi, please upgrade, and let us know if you have any other issues in a separate ticket ..

See here for releases with release notes https://github.com/farridav/django-jazzmin/releases

Thanks :)
