### ISSUE TITLE
TemplateDoesNotExist at /admin2/filer/folder/1/list/ admin/filer/folder/directory_table.html

### ISSUE THREAD

**Issue by housUnus** [farridav/django-jazzmin#500]
Hi i had this problem using jazzmin with the latest version of Filer:

I found out that changing:
{% include "admin/filer/folder/directory_table.html" %}

to 

{% include "admin/filer/folder/directory_table_list.html" %}

in

**jazzmin\templates\admin\filer\folder\directory_listing.html** 

Solved the problem.

**Comment by reedjones** [comment]
Had the same problem, above solution worked..
