### ISSUE TITLE
UI only working in the login and logout page.

### ISSUE THREAD

**Issue by SagunDevkota** [farridav/django-jazzmin#513]
I am trying to use django-jazzmin for my admin panel but, the content of my page seems wierd.
here are the list of my installed apps:
INSTALLED_APPS = [
    "jazzmin",
    "admincharts",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_elasticsearch_dsl',
    'django_elasticsearch_dsl_drf',
    "corsheaders",
    'ckeditor',
    'django_celery_beat',
    'core',
    'user',
    'product',
    'payment',
    'address',
    'discount'
]

I have not tinkered with any settings. The UI looks like documentation only in login and logout page.
<img width="1512" alt="Screenshot 2023-10-06 at 10 13 43 PM" src="https://github.com/farridav/django-jazzmin/assets/55743561/4240ef43-f0f0-4d0a-a730-a2e0b19ce1dc">

**Comment by AliYmn** [comment]
@SagunDevkota hello, My guess is that INSTALLED_APPS may be occurring due to the package ordering you mentioned.

Please try it like this;

```
INSTALLED_APPS = [
"admincharts",
"jazzmin", # It must be defined before admin.
'django.contrib.admin',
...
]
```

**Comment by PacificGilly** [comment]
Closing now due to inactivity, but feel free to reply if you're still having issues. Thanks.
