### ISSUE TITLE
logout button not work

### ISSUE THREAD

**Issue by tra007** [farridav/django-jazzmin#522]
log out button send data GET method but it should be send it POST method.

**Comment by AliYmn** [comment]
@tra007 Hello, I have opened a Pull Request related to the logout issue: https://github.com/farridav/django-jazzmin/pull/523

**Comment by jamesgilmorelyst** [comment]
Hey @tra007, a PR was merged today (https://github.com/farridav/django-jazzmin/pull/544) to fix this issue. A new release will be needed to release this fix.

**Comment by PacificGilly** [comment]
Apologies for the delay, but we've released the fix to resolve the logout issue now:

- https://github.com/farridav/django-jazzmin/releases/tag/v3.0.0

If you are still supporting an older version of Python (<3.8) or Django (<4), then we also have released a fix for this version as well:
- https://github.com/farridav/django-jazzmin/releases/tag/v2.6.2
