### ISSUE TITLE
Method Not Allowed (GET): /admin/logout/

### ISSUE THREAD

**Issue by 8bitaby** [farridav/django-jazzmin#536]
While logging out the admin, rather than performing a POST the template performs a GET operation which raises an error saying:
####
Method Not Allowed (GET): /admin/logout/
Method Not Allowed: /admin/logout/
GET /admin/logout/ HTTP/1.1" 405 0
###

- Issue is in /jazzmin/templates/admin/base.html --- and search for logout then,

- change this
                       ` <a href="{% url 'admin:logout' %}" class="dropdown-item">`
                       `<i class="fas fa-users mr-2"></i> {% trans 'Log out' %}`
                       `</a>`

-    to this
                        `<form action="{% url 'admin:logout' %}" method="post">`
                            `{% csrf_token %}`
                            `<button type="submit" class="dropdown-item">`
                             `   <i class="fas fa-users mr-2"></i> {% trans 'Log out' %}`
                            `</button>`
                        `</form>`

**Comment by sa11erto5n** [comment]
the view:
```
def logout_user(request):
    logout(request)
    return redirect('admin:index')
```
the modified line of base.html:
```<a href="{% url 'jazzmin_dev:logout' %}" class="dropdown-item">```

**Comment by jamesgilmorelyst** [comment]
Hi @8bitaby, a PR was merged today (https://github.com/farridav/django-jazzmin/pull/544) to fix this issue. A new release will be needed to release this fix.

**Comment by jumaantony** [comment]
When will this be sorted? I have just installed the new version but still it aint wworking.

**Comment by ExcelentProgrammer** [comment]
+

**Comment by PacificGilly** [comment]
Apologies for the delay, but we've release the fix to resolve the logout issue now:

- https://github.com/farridav/django-jazzmin/releases/tag/v3.0.0

If you are still supporting an older version of Python (<3.8) or Django (<4) then we also have release a fix for this version as well:
- https://github.com/farridav/django-jazzmin/releases/tag/v2.6.2
