### ISSUE TITLE
Django-jazzmin logout 405 error

### ISSUE THREAD

**Issue by ExcelentProgrammer** [farridav/django-jazzmin#558]
Django-jazzmin logout 405 error

**Comment by workshop22** [comment]
i just installed jazzmin and i'm getting the same error

**Comment by PacificGilly** [comment]
Thanks for raising the issue with us. We've resolved the issue, but still need to release a new version of django-jazzmin. Please bear with us while we release this in the coming days

**Comment by sriraj66** [comment]
Thank you please sort it out by changing

<form method="POST" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit">logout</button>
</form>

**Comment by PacificGilly** [comment]
Apologies for the delay, but we've release the fix to resolve the logout issue now:

- https://github.com/farridav/django-jazzmin/releases/tag/v3.0.0

If you are still supporting an older version of Python (<3.8) or Django (<4) then we also have release a fix for this version as well:
- https://github.com/farridav/django-jazzmin/releases/tag/v2.6.2

**Comment by UnoYakshi** [comment]
As of 3.0.0, I still have GET method:

![image](https://github.com/user-attachments/assets/3a0c3ddb-7107-4af7-a9d3-c87315a63c15)


Yet I see the code from the PR being POST (`.venv/lib64/python3.12/site-packages/jazzmin/templates/admin/base.html`):

![image](https://github.com/user-attachments/assets/86b9bb89-8df0-4f67-8c48-45efe3c4720a)
