### ISSUE TITLE
Invalid filter: 'length_is' in change_form with Django 5.1

### ISSUE THREAD

**Issue by guercusguo** [farridav/django-jazzmin#593]
Due to:
The length_is template filter is removed in [**Features removed in 5.1**.](https://docs.djangoproject.com/en/5.1/releases/5.1/)

<p>In template <code>/env/lib/python3.12/site-packages/jazzmin/templates/admin/includes/fieldset.html</code>, error at line <strong>22</strong></p>
   <h3>Invalid filter: 'length_is'</h3>
   
12 | <div class="card-title">
-- | --
{{ fieldset.description }}
</div>
</div>
{%endif%}
 
<div class="p-5{% if fieldset.name %} card-body{% endif %}">
{% endif %}
 
{% for line in fieldset %}
<div class="form-group{% if line.fields\|length_is:'1' and line.errors %} errors{% endif %}{% if not line.has_visible_field %} hidden{% endif %}{% for field in line %}{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% endfor %}">
<div class="row">
{% for field in line %}
<label class="{% if not line.fields\|length_is:'1' and forloop.counter != 1 %}col-auto {% else %}col-sm-3 {% endif %}text-left" for="id_{{ field.field.name }}">
{{ field.field.label\|capfirst }}
{% if field.field.field.required %}
<span class="text-red">* </span>
{% endif %}
</label>
<div class="{% if not line.fields\|length_is:'1' %} col-auto  fieldBox {% else %} col-sm-7 {% endif %}
{% if field.field.name %} field-{{ field.field.name }}{% endif %}

**Comment by collinsinclair** [comment]
Also seeing this - is there a known fix?

**Comment by krv006** [comment]
This is solution, change your django version, downgrade to 5.0.1

`pip3 install django==5.0.1`

**Comment by ronny-rentner** [comment]
As a temporary workaround, copy over the file `templates/admin/includes/fieldset.html` from jazzmin to your project and replace the `length_is` filter as explained in the Django release notes: https://docs.djangoproject.com/en/5.1/releases/4.2/#id1

My working `fieldset.html` for Django 5.1 looks like this now:
```
{% load jazzmin %}
{% if card %}
<div class="card {{ fieldset.classes|cut:"collapse" }}">
    {% if card_header and fieldset.name %}
        <div class="card-header">
            <div class="card-title">
                <strong>{{ fieldset.name }}</strong>{% if fieldset.description %} - <i>{{ fieldset.description }}</i>{% endif %}
            </div>
        </div>
    {%elif fieldset.description %}
    <div class="card-header">
        <div class="card-title">
            {{ fieldset.description }}
        </div>
    </div>
    {%endif%}

    <div class="p-5{% if fieldset.name %} card-body{% endif %}">
{% endif %}

    {% for line in fieldset %}
    <div class="form-group{% if line.fields|length == 1 and line.errors %} errors{% endif %}{% if not line.has_visible_field %} hidden{% endif %}{% for field in line %}{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% endfor %}">
        <div class="row">
            {% for field in line %}
                <label class="{% if not line.fields|length == 1 and forloop.counter != 1 %}col-auto {% else %}col-sm-3 {% endif %}text-left" for="id_{{ field.field.name }}">
                    {{ field.field.label|capfirst }}
                    {% if field.field.field.required %}
                    <span class="text-red">* </span>
                    {% endif %}
                </label>
                <div class="{% if not line.fields|length == 1 %} col-auto  fieldBox {% else %} col-sm-7 {% endif %}
                             {% if field.field.name %} field-{{ field.field.name }}{% endif %}
                             {% if not field.is_readonly and field.errors %} errors{% endif %}
                             {% if field.field.is_hidden %} hidden {% endif %}
                             {% if field.is_checkcard %} checkcard-row{% endif %}">
                    {% if field.is_readonly %}
                        <div class="readonly">{{ field.contents }}</div>
                    {% else %}
                        {{ field.field }}
                    {% endif %}
                    <div class="help-block red">
                        {% if not line.fields|length == 1 and not field.is_readonly %}{{ field.errors }}{% endif %}
                    </div>
                    {% if field.field.help_text %}
                        <div class="help-block">{{ field.field.help_text|safe }}</div>
                    {% endif %}
                    <div class="help-block text-red">
                        {% if line.fields|length == 1 %}{{ line.errors }}{% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}

{% if card %}
    </div>
</div>
{% endif %}
```

**Comment by krv006** [comment]
you must be install Django==5.0.1 because Django update 7 days ago and you
can read https://docs.djangoproject.com/en/5.1/releases/5.1/  this web sayt


ср, 14 авг. 2024 г. в 13:01, Ronny Rentner ***@***.***>:

**Comment by JargeZ** [comment]
Hope that #519 will be merged

**Comment by daniel-devi** [comment]
> As a temporary workaround, copy over the file `templates/admin/includes/fieldset.html` from jazzmin to your project and replace the `length_is` filter as explained in the Django release notes: https://docs.djangoproject.com/en/5.1/releases/4.2/#id1
> 
> My working `fieldset.html` for Django 5.1 looks like this now:
> 
> ```
> {% load jazzmin %}
> {% if card %}
> <div class="card {{ fieldset.classes|cut:"collapse" }}">
>     {% if card_header and fieldset.name %}
>         <div class="card-header">
>             <div class="card-title">
>                 <strong>{{ fieldset.name }}</strong>{% if fieldset.description %} - <i>{{ fieldset.description }}</i>{% endif %}
>             </div>
>         </div>
>     {%elif fieldset.description %}
>     <div class="card-header">
>         <div class="card-title">
>             {{ fieldset.description }}
>         </div>
>     </div>
>     {%endif%}
> 
>     <div class="p-5{% if fieldset.name %} card-body{% endif %}">
> {% endif %}
> 
>     {% for line in fieldset %}
>     <div class="form-group{% if line.fields|length == 1 and line.errors %} errors{% endif %}{% if not line.has_visible_field %} hidden{% endif %}{% for field in line %}{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% endfor %}">
>         <div class="row">
>             {% for field in line %}
>                 <label class="{% if not line.fields|length == 1 and forloop.counter != 1 %}col-auto {% else %}col-sm-3 {% endif %}text-left" for="id_{{ field.field.name }}">
>                     {{ field.field.label|capfirst }}
>                     {% if field.field.field.required %}
>                     <span class="text-red">* </span>
>                     {% endif %}
>                 </label>
>                 <div class="{% if not line.fields|length == 1 %} col-auto  fieldBox {% else %} col-sm-7 {% endif %}
>                              {% if field.field.name %} field-{{ field.field.name }}{% endif %}
>                              {% if not field.is_readonly and field.errors %} errors{% endif %}
>                              {% if field.field.is_hidden %} hidden {% endif %}
>                              {% if field.is_checkcard %} checkcard-row{% endif %}">
>                     {% if field.is_readonly %}
>                         <div class="readonly">{{ field.contents }}</div>
>                     {% else %}
>                         {{ field.field }}
>                     {% endif %}
>                     <div class="help-block red">
>                         {% if not line.fields|length == 1 and not field.is_readonly %}{{ field.errors }}{% endif %}
>                     </div>
>                     {% if field.field.help_text %}
>                         <div class="help-block">{{ field.field.help_text|safe }}</div>
>                     {% endif %}
>                     <div class="help-block text-red">
>                         {% if line.fields|length == 1 %}{{ line.errors }}{% endif %}
>                     </div>
>                 </div>
>             {% endfor %}
>         </div>
>     </div>
>     {% endfor %}
> 
> {% if card %}
>     </div>
> </div>
> {% endif %}
> ```

Tnxs, i was wondering if I didn't do something right, because I used it 3 weeks ago with Django 5.0 it worked, I was like why

**Comment by AndrewManHayChiu** [comment]
To clarify the above comment, you should have a folder specified in your settings.py file for 'templates':

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'templates',
            ],
        'APP_DIRS': True,
        ...
   }
]
```

Then copy the file from the previous comment into the 'templates' using the same path as the file in the jazzmin package, like templates\admin\includes\fieldset.html.

Then copy/edit the file so that it matches the above.

**Comment by FabianClemenz** [comment]
This has been fixed with https://github.com/farridav/django-jazzmin/releases/tag/v3.0.1

**Comment by imvickykumar999** [comment]
> This is solution, change your django version, downgrade to 5.0.1
> 
> `pip3 install django==5.0.1`

Since `length_is` is deprecated since `Django 4.2` and removed in `Django 5.1`

See changes : https://github.com/farridav/django-jazzmin/pull/519/commits/15b4ed076a2db0e65b6ad32bd9d459f4a85ccceb

You can use `pip install Django==4.1.*` to fix issue.
