### ISSUE TITLE
Horizontal layout of the input forms

### ISSUE THREAD

**Issue by SultanovvAsadbek** [farridav/django-jazzmin#597]
![Screenshot from 2024-09-08 14-39-51](https://github.com/user-attachments/assets/8cca2e26-51d3-42bd-90f9-23c77aa2a38f)
I would like the input form to be located not under the **title**, but to the right of it.

![Screenshot from 2024-09-08 14-52-22](https://github.com/user-attachments/assets/5ea3cc92-4afb-4aa5-b79e-9a6528769d5a)

**Comment by Tchy258** [comment]
You can do this within a django [ModelAdmin](https://docs.djangoproject.com/en/5.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets) class by nesting the fields you want in the same row as a tuple in the `fieldsets` property, it's unrelated to jazzmin itself.
```python
class MyModelAdmin(admin.ModelAdmin):
    fieldsets = (
        ('Some name', {
            'fields': ( 
                ('first field', 'second field',),)
        }),
    )
```
If it's an inline admin model, the same logic applies, in your particular case it should be something like this
```python
class UnitInline(admin.StackedInline):
    model = Unit # This is where your model class goes
    verbose_name_plural = "Some name" # This is how you want the tab to be named like
    fieldsets = (
        (None, {
            'fields': (
                ('title','type',),
            ),
        }),
    )
```

**Comment by katiam2** [comment]
Thanks @Tchy258. Closing as completed
