### ISSUE TITLE
M2M filter selects need some jazz

### ISSUE THREAD

**Issue by TysonRV** [farridav/django-jazzmin#64]
It does look a bit dull at the moment:
![Screenshot 2020-06-18 at 09 43 25](https://user-images.githubusercontent.com/22962693/84999032-86781600-b148-11ea-88a3-fd6df9fdd6a5.png)

We could use something like bootstrap duallistbox for this one, which can be found here:
https://adminlte.io/themes/v3/pages/forms/advanced.html

![Screenshot 2020-06-18 at 09 44 50](https://user-images.githubusercontent.com/22962693/84999016-7ceeae00-b148-11ea-9a29-3443dcadbf08.png)

**Comment by farridav** [comment]
Closing in favour of a bug fix or voluntary PR
