### ISSUE TITLE
Enhancement: Jazz the Change Form Tabs

### ISSUE THREAD

**Issue by RamezIssac** [farridav/django-jazzmin#65]
The implemented behavior is to add a tab called "General" if no fieldset , which might not always be relevant. I suggest if no fieldset, build the form right away (without tabs).

Also maybe there can be an option to skip the tabs and display the page in one unit . 
(Example: An invoice model with invoice details )

**Comment by farridav** [comment]
Sure, that seems reasonable, Ive made a PR to effect this change See https://github.com/farridav/django-jazzmin/pull/67
