### ISSUE TITLE
Login Page Title Problem

### ISSUE THREAD

**Issue by Estanzem** [farridav/django-jazzmin#75]
![problem](https://user-images.githubusercontent.com/67423235/85727312-91f6ae80-b6ff-11ea-8401-baf632bd24bc.PNG)
First of all, thank you very much for writing such an admin panel interface. Please do not stop the enhancements.

But the title does not appear on the login page. I would be very glad if you check. Achievements.

**Comment by Estanzem** [comment]
> 
> 
> First of all, thank you very much for writing such an admin panel interface. Please do not stop the enhancements.
> 
> But the title does not appear on the login page. I would be very glad if you check. Achievements.

![problem](https://user-images.githubusercontent.com/67423235/85727230-84412900-b6ff-11ea-823b-c095d359c3a2.PNG)

**Comment by farridav** [comment]
Ah yes, I can see that needs sorting and it's a quick fix.

@TysonRV do you have time to look at this ? The login page is quite separate from the rest of the site, perhaps it should extend base_site.html. if not I'll sort it tomorrow .

@Estanzem thanks for reporting :)

**Comment by TysonRV** [comment]
@farridav don't worry, will sort it now

@Estanzem thanks for letting us know! 🙂
