### ISSUE TITLE
more configurations options

### ISSUE THREAD

**Issue by saileshkush95** [farridav/django-jazzmin#78]
This project is awesome but still missing some of the configurations features. like fixed navbar and fixed sidebar as will as fixed footer. Sticky section for action button somethings like this. 
[Sticky Section for event in calendar page](https://adminlte.io/themes/v3/pages/calendar.html)

**Comment by farridav** [comment]
Sounds good, we've been looking for new options to put in the UI builder...

**Comment by farridav** [comment]
Closing, as we have implemented these
