### ISSUE TITLE
apps not shown

### ISSUE THREAD

**Issue by navi380** [farridav/django-jazzmin#99]
I have 5 apps installed in my project which are working fine for me in my Django admin. But i installed jazzmin admin everything is working fine for now but its shows me only 3 apps. further my other 2 apps name start with capital letter. i tried to rename them and check it again but it didn't resolve my issue.

**Comment by farridav** [comment]
Can you post your jazzmin config here ? We will try to repro.

Screenshots can also be a great help if possible

**Comment by navi380** [comment]
I was sure that may be this was name problem..  Cause only two apps have
name start with capital letters  like Order and Reviews..  And that are not
showing  in admin side..
So i chang the names by refactor but thats doesn't  work so  delete those
apps and again start new apps with small letters and did copy the code
there now its working  fine for me..  Its showing  me both of them as well

**Comment by navi380** [comment]
`[](url)`

**Comment by navi380** [comment]
'jazzmin',
 'django.contrib.admin',


JAZZMIN_SETTINGS = {
    # title of the window
    'site_title': 'shopna Admin',

    # Title on the brand, and the login screen (19 chars max)
    'site_header': 'Shopna',

    # square logo to use for your site, must be present in static files, used for favicon and brand on top left

    # Welcome text on the login screen
    'welcome_sign': 'Welcome to Shopna Admin',

    # Copyright on the footer
    'copyright': 'Acme Ltd',

    # The model admin to search from the search bar, search bar omitted if excluded
    'search_model': 'auth.User',

    # Field name on user model that contains avatar image
    'user_avatar': None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    'topmenu_links': [

        # Url that gets reversed (Permissions can be added)
        {'name': 'Home',  'url': 'admin:index', 'permissions': ['auth.view_user']},


        # model admin to link to (Permissions checked against model)
        {'model': 'auth.User'},


    ],

    #############
    # User Menu #
    #############



    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    'show_sidebar': True,

    # Whether to aut expand the menu
    'navigation_expanded': True,

    # Hide these apps when generating side menu e.g (auth)
    'hide_apps': [],

    # Hide these models when generating side menu (e.g auth.user)
    'hide_models': [],

    # List of apps to base side menu ordering off of (does not need to contain all apps)
    'order_with_respect_to': ['accounts', 'polls',],

    # Custom links to append to app groups, keyed on app name
    'custom_links': {
        'polls': [{
            'name': 'Make Messages',
            'url': 'make_messages',
            'icon': 'fa-comments',
            'permissions': ['polls.view_poll']
        }]
    },

    # Custom icons for side menu apps/models See https://www.fontawesomecheatsheet.com/font-awesome-cheatsheet-5x/
    # for a list of icon classes
    'icons': {
        'auth': 'fa-users-cog',
        'auth.user': 'fa-user',
        'auth.Group': 'fa-users',
    },
    # Icons that are used when one is not manually specified
    'default_icon_parents': 'fa-chevron-circle-right',
    'default_icon_children': 'fa-circle',

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "single",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs",},
}

![Screenshot (83)](https://user-images.githubusercontent.com/63947906/89396893-9368bd00-d728-11ea-8f7a-4f01a04788fd.png)

**Comment by navi380** [comment]
now issue is resolved when i recreate apps with small letter. Thanks and good work u change the admin side to whole new level.

**Comment by farridav** [comment]
I'm glad you found a way forwards, but this is also a bug on our side, I've put up a fix and a test for it here 

https://github.com/farridav/django-jazzmin/pull/100 

Ill try to put some time in to check any other areas where app name casing has a negative impact :)

Thanks again

**Comment by navi380** [comment]
No Problem....  Its fine..  Keep it up

**Comment by mpibpc-mroose** [comment]
I think there may be a problem with [get_admin_url](https://github.com/farridav/django-jazzmin/blob/2b51e6ee1efeaea415376a4fe6b1175d2362e1ad/jazzmin/utils.py#L49) and apps named in CamelCase.

Given we have an app named `CamelStore' and inside a model named `CamelType` the admin change list name for that would be `admin:CamelStore_cameltype_changelist`. As `get_admin_url'  converts the whole string with `lower()` that would result in a non resolvable admin url.

Just removing the `lower()`call in  [line 50](https://github.com/farridav/django-jazzmin/blob/2b51e6ee1efeaea415376a4fe6b1175d2362e1ad/jazzmin/utils.py#L50) should solve that problem.
